### ISSUE TITLE
Export returned types (Typescript)

### ISSUE THREAD

**Issue by omrishaked** [amz-tools/amazon-sp-api#107]
I'm trying to use the package in my Typescript project, but most of the returned types aren't exported.

For example, in the `finances` endpoint, I'm calling the `listFinancialEventGroups` operation, which returns a list of `FinancialEventGroup` objects, but I can't have my function return the same type because `FinancialEventGroup` isn't exported.

This also applies to *many* other types (see https://github.com/amz-tools/amazon-sp-api/blob/main/lib/typings/operations/finances.ts, only half of the interfaces there are exported).

Wanted to make sure I'm using it correctly, and that my request makes sense.  If so, yes, I'll submit a PR, thank!

**Comment by omrishaked** [comment]
We all actually, the README instructs to export only the response interfaces and not the contained interfaces as well, and I think *all* relevant interfaces should be exported, in order for users to be able to use those interfaces in the functions as well.

Similar to my previous example, I’d like to write a function that returns a list of FinancialEventGroups (and uses SellingPartnerAPI internally).

Would exporting all interfaces make sense here?

**Comment by omrishaked** [comment]
For example, if we export all existing interfaces, users will be able to use them like this:
```
import { FinancialEventGroup } from 'amazon-sp-api/lib/typings/operations/finances';
```

**Comment by omrishaked** [comment]
If that makes sense, please review https://github.com/amz-tools/amazon-sp-api/pull/108, thanks!

**Comment by omrishaked** [comment]
Hey @amz-tools, got time to look at the PR please?

**Comment by amz-tools** [comment]
Hi @omrishaked,

I wouldn't really see anything that stands against that, I just merged your PR.

**Comment by omrishaked** [comment]
Thanks!  How/when does that get released and published to npmjs?

**Comment by amz-tools** [comment]
Working on it right now, hopefully will release a new version later on today.
