### ISSUE TITLE
API_PATH No longer available

### ISSUE THREAD

**Issue by iamsr** [amz-tools/amazon-sp-api#109]
Please update the documentation as the call API doesn't allow to set api_path as it's not the part of the object. Let me know if it's right or not.

**Comment by amz-tools** [comment]
Hi @iamsr,

it should work fine. Just tried the following without any issues:

```
let res = await sellingPartner.callAPI({
  api_path:'/catalog/2020-12-01/items/B084DWG2VQ',
  query:{
    marketplaceIds:['A1PA6795UKMFR9'],
    includedData:['identifiers', 'images', 'productTypes', 'salesRanks', 'summaries', 'variations']
  },
  method:'get'
});
console.log(res);
```

**Comment by iamsr** [comment]
in the latest code when you see the definition of request parameter it's something like this

![image](https://user-images.githubusercontent.com/24357511/154495875-cebde286-4da1-467e-b8cb-f67f70517b5e.png)

which showing error in typescript

**Comment by amz-tools** [comment]
Ah, I see. Yes, regarding TypeScript the package is not up to date will plain JS, its still missing in the TypeScript definition. Feel free to add more interfaces and/or parameters to the TypeScript definitions.
