### ISSUE TITLE
InvalidSignature Error Inconsistently  

### ISSUE THREAD

**Issue by steven-so** [amz-tools/amazon-sp-api#112]
Thank you for building this tool. It has made working with the SP-API possible for me. 

Occasionally, and somewhat randomly, I run into Invalid Token or "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method..." error messages but have not been able to figure out the cause. The strange part is that sometimes I can make the same request without changing anything and then it will suddenly work. 

There is one case today where I consistently get the InvalidSignature error when I make the request for a particular Asin (using fetchImages below), but I can change request to different Asin without changing anything else the request works fine. So I'm a bit baffled. 

```
fetchImages: async (req, res) => {
    const { asin } = req.body;
    try {
      let sellingPartner = new SellingPartnerAPI({
        region: "na",
        refresh_token: REFRESH_TOKEN,
        options: {
          use_sandbox: false,
        },
      });

      let amzRes = await sellingPartner.callAPI({
        operation: "getCatalogItem",
        endpoint: "catalogItems",
        query: {
          marketplaceIds: ["ATVPDKIKX0DER"],
          includedData: ["images"],
        },
        path: {
          asin: asin,
        },
        options: {
          version: "2020-12-01",
        },
      });
      console.log(amzRes);
      res.status(200).send(amzRes);
    } catch (e) {
      console.log(e);
      res.status(500).send(e);
    }
  },
  ```
  
  Thanks for your time. Any advice is greatly appreciated.

**Comment by amz-tools** [comment]
Hi @steven-so,

just tried your script with a random ASIN, it works perfectly fine. I think maybe the issue might be somewhere with what `req.body` returns in the first place.

**Comment by steven-so** [comment]
Thanks for trying it @amz-tools 

I added a console.log to see what "asin" from req.body was and it looks correct (B097WQ2BFW), and I still got the error.  

(B097WQ2BFW is the asin I mentioned above that I can't get to work today.)

I'm doing an axios request to my fetchImages endpoint. Could that cause any problems with the signature even if the asin variable is correct? 

```
    axios
      .post("/myController/fetchImages", { asin })
      .then(async (res) => {
        setImages(res.data.images[0].images);
      })
      .catch((e) => {
        console.log(e);
      });
```

**Comment by amz-tools** [comment]
I wouldn't think so, which version of the client are you using? And maybe you can try calling the operation by hard coding the  asin and/or run the part isolated to see if the issue still persists then.

**Comment by steven-so** [comment]
AH figured it out!

I was using: 
  "amazon-sp-api": "^0.5.4",
  "axios": "^0.21.4",

Then upgraded to: 
  "amazon-sp-api": "^0.7.1",
  "axios": "^0.26.0",

That alone didn't fix the issue... however then the error message changed: 
```
CustomError: Invalid 'asin' provided.
  ...
  code: 'InvalidInput',
  details: '',
  type: 'error'
}
```
The asin still looked correct, but then I did the .trim() method on the asin and it worked... There was a leading space on the asin. 🤦

Thanks for helping me. 😊
