### ISSUE TITLE
Unable to create Feed: Error: Invalid request parameters

### ISSUE THREAD

**Issue by rogerms** [amz-tools/amazon-sp-api#124]
I am following all the instructions but for some reasons I am getting an error when trying to create a feed.
 Here is the error which doesn't show which parameters are invalid:
```
 	"code": "InvalidInput",
	"message": "Invalid request parameters",
	"details": "",
	"type": "error",
	"stacktrace": [
		"Error: Invalid request parameters", ...
```
Do you guys have any idea?
I've been able to fetch orders, etc. 
I can even update inventory using the "patchListingsItem" operation; that tells me that my credentials are valid. 

here is the code: 
```
  async createFeed2(input: any) {
    let feed = {
      content: `<?xml version="1.0" encoding="utf-8"?>
        <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
          <Header>
            <DocumentVersion>1.02</DocumentVersion>
            <MerchantIdentifier>YOUR_MERCHANT_IDENTIFIER</MerchantIdentifier>
          </Header>
          <MessageType>Inventory</MessageType>
          <Message>
            <MessageID>1</MessageID>
            <Inventory>
              <SKU>YOUR_SKU</SKU>
              <Quantity>10</Quantity>
            </Inventory>
          </Message>
        </AmazonEnvelope>`,
      contentType: 'text/xml; charset=utf-8',
    };

    let request: any = {
      operation: 'createFeedDocument',
      endpoint: 'feeds',
      body: {
        contentType: feed.contentType,
      },
    };
    let feed_upload_details = await this.sellingPartner.callAPI(request);

    let res = await this.sellingPartner.upload(feed_upload_details, feed);

    request = {
      operation: 'createFeed',
      endpoint: 'feeds',
      body: {
        marketplaceIds: ['A1PA6795UKMFR9'],
        feedType: 'POST_INVENTORY_AVAILABILITY_DATA',
        inputFeedDocumentId: feed_upload_details.feedDocumentId,
      },
      options: {
        version: '2021-06-30',
      },
    };
    let feed_creation_infos = await this.sellingPartner.callAPI(request);
    console.log('feed_creation_infos', feed_creation_infos);
    return feed_creation_infos;
  }
```
Thank you for your help

**Comment by DoogieStick** [comment]
@rogerms it's not a problem with your code, the library broke, I followed the same steps and it worked some days ago, but some days ago started returning this error. If you see on the url they return the signature doesn't match (I opened a ticket as well about this error, #125 ). Now let's wait they to answer about a solution for all.

**Comment by amz-tools** [comment]
Hi @rogerms, @DoogieStick,

which version of the client are you using? I am wondering what could be the issue here, I just tried the exact same feed upload call and it is actually working without any problems. Are you sure that the merchant identifier and/or SKU are correct?

**Comment by amz-tools** [comment]
Hi @DoogieStick,

ah yes, I see the code, sorry! Its really bugging me, both of your codes look perfectly fine. And when I am trying the code (only changing merchant identifier and sku) I can update the quantity without any issues and can also see the quantity change in sellercentral.
Checking the resullt with `getFeedDocument` also states that everything worked out fine:
```
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.02</DocumentVersion>
		<MerchantIdentifier>MERCHANT_IDENTIFIER</MerchantIdentifier>
	</Header>
	<MessageType>ProcessingReport</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<ProcessingReport>
			<DocumentTransactionID>DOCUMENT_TRANSACTION_ID</DocumentTransactionID>
			<StatusCode>Complete</StatusCode>
			<ProcessingSummary>
				<MessagesProcessed>1</MessagesProcessed>
				<MessagesSuccessful>1</MessagesSuccessful>
				<MessagesWithError>0</MessagesWithError>
				<MessagesWithWarning>0</MessagesWithWarning>
			</ProcessingSummary>
		</ProcessingReport>
	</Message>
</AmazonEnvelope>
```
So to be honest, I am a bit lost here as to what could be the issue. But one thing i am wondering: @DoogieStick, you wrote that the error started coming with version 0.6.5 after some time and already BEFORE you upgraded to 0.7.3? So if the version didn't change it probably wouldn't be related to the client?

**Comment by DoogieStick** [comment]
@amz-tools  I developed this feature in January, it worked perfectly at this point in time.
some days ago I tried to execute the same code and started to get this error. after looking at your npm site I found new versions. So I started testing going up/down between versions from 0.7.3 to 0.6.4, but out of the version I settle I got the same error about the signature (the same error Roger said on the api, but on the link specified it was signature error(

**Comment by amz-tools** [comment]
@DoogieStick, @rogerms,

to me this looks like an issue on Amazon's end, because what seems to happen here is exactly the same as mentioned in the two tickets [here](https://github.com/amzn/selling-partner-api-docs/issues/867) and [here](https://github.com/jlevers/selling-partner-api/issues/175). Also, I couldn't really think of a reason why the code works fine and then suddenly doesn't work anymore without any version update of the client.

Maybe its possible to have it resolved by opening a ticket with Amazon SP support, because according to the devs raising the issues mentioned above that's apparently the only way to fix the issue...

**Comment by mcbrideke** [comment]
I am having this same issue as well, has anyone had any luck contacting amazon to get this resolved?

**Comment by nabilsarder** [comment]
I came across this issue today. No changes in the code or library version. Any update on this? I am able to call createFeedDocument and upload the feed content. Calling createFeed returns `CustomError: Invalid request parameters`.

**Comment by nabilsarder** [comment]
Check your seller account email for any mail stating that your ability to create listing has been disabled. Updating the Charge Method should resolve this issue.

**Comment by wangjue666** [comment]
> Invalid request parameters

I just met and solved this problem！

First, you enter your authorized Amazon store，Manually click to create product，Then Amazon will prompt you that the store needs to be activated。Then you need to resubmit the information and wait for the approval ！

**Comment by wangjue666** [comment]
This is because the store has not used it for a long time, and the **FEED** has been disabled by Amazon. 

this is not **Signature error**!
