### ISSUE TITLE
Reports charsets

### ISSUE THREAD

**Issue by jesusvalle** [amz-tools/amazon-sp-api#144]
Good morning,

When downloading reports from Amazon, with this api we must indicate the charset (utf8 or cp1252) to decode it.

I have seen that when downloading the report, in the header of the response, we have the content type

Wouldn't it be more optimal to parse this value and use it for decoding? 

For example, the merchant listings all data reports in Europe are encoded with the type cp1252, while in america, they use the utf8 encoding. Specifying the charset manually means having to make custom definitions by report type and region, and with this method it would no longer be necessary.

Examples: 

Merchant Listings All Data response content type (USA - Canada)
`content-type:
'text/plain; charset=utf8'
`
Merchant Listings All Data response content type (Europe - Spain)
`'content-type:
text/plain; charset=Cp1252'`

Regards.

**Comment by amz-tools** [comment]
Hi @jesusvalle, that sounds like a smart idea. We'll have a look at it as soon as possible.

**Comment by amz-tools** [comment]
Hi @jesusvalle, works fine, we added the functionality in version v0.7.9. Anyway the possibility of overwriting the charset taken from `content-type` header by setting it explicitly via options is still in place.
