### ISSUE TITLE
Requests do not timeout in case of network problem

### ISSUE THREAD

**Issue by colin-brown** [amz-tools/amazon-sp-api#147]
When a large volume of API requests are sent, inevitably network errors will occasionally prevent some requests from succeeding.

Currently this can cause code that uses this npm to hang if Amazon's server doesn't start or complete a request.

One current code base I work on uses superagent to perform the https requests and sets deadline and response timeouts, which has proved to be very useful in practice:

 *  response timeout is time between sending request and receiving the first byte of the response. Includes DNS and connection time.
 * deadline is the time from start of the request to receiving response body in full. If the deadline is too short large files may not load at all on slow connections

I will create a pull request with an implementation for your consideration.

**Comment by colin-brown** [comment]
I've created a pull request (see above), please let me know if this is something you would consider adding. I designed the code so that it is functionally identical to the current version unless the new options are specified when making a request. Happy to provide more detail on the modifications I made if that helps. Thanks!

**Comment by amz-tools** [comment]
Hi @colin-brown,

thank you for the PR and sorry for being a bit slow these days in responding. We checked it out and like the idea of it.
 
However I was wondering why you are not using the default [.setTimeout](https://nodejs.org/api/http.html#requestsettimeouttimeout-callback) function? This should do exactly what you describe as the response timeout, or am I missing something?

Concerning the deadline timeout: What is the reason of having a timeout firing after X time regardless of the fact that its still receiving data or not? Wouldn't it be better to fire the deadline timeout only when there is no more data coming in after X time? This would also prevent an error for the case of large files on slow connections that you describe above.

**Comment by colin-brown** [comment]
Hi,

Initially I did use the default [.setTimeout](https://nodejs.org/api/http.html#requestsettimeouttimeout-callback) function but during I tested I realised this only sets a timeout before the TCP socket is established. This is less useful as the socket can connect, but the Amazon server may still not respond, leaving the calling script hanging waiting for a response.

The response timeout my code implements is similar but will also catch the case where the socket connects and then the Amazon server does not start sending a reply.

The deadline timeout is useful for the case where a network error interrupts a partially completed response. In our use we typically set this for 30 seconds for API calls that usually complete in less than 1 second - it is a sort of failsafe to prevent the code from hanging when this kind of network error occurs. 

If a large files or slow connection is expected, you might prefer not use the deadline or might set it much higher, to some value several times higher than the maximum time you expect the call & response to take.

As mentioned I have attempted to implement the same approach used by the fairly mature [superagent](https://visionmedia.github.io/superagent/#timeouts) module.

**Comment by amz-tools** [comment]
@colin-brown,

okay, got it, I think we can work with it like this. I would suggest two more ideas though:

What do you think if we also add a third timeout option that would basically do what I described in my last comment? Something like an idle_timeout that will fire when the request has started but for some reason is stalled in the middle.

Example: We have a very large report that downloads fine for 5 seconds, but is then stalled. If we have a deadline timeout of maybe 120 seconds (because we expect a very large file with a long download time) it would only fire after that time, but if we also include an idle timeout of maybe 30 seconds it would fire after 35 seconds already.

And the other idea would be to add the timeout option to the initial class config as well so that its possible to set these values for all calls of a class instance.

And one for idea: Do you think it would make sense if we make a timeout object instead of single values? So to say timeout.response, timeout.deadline and timeout.idle?

**Comment by colin-brown** [comment]
> @colin-brown,
> 
> okay, got it, I think we can work with it like this. I would suggest two more ideas though:
> 
> What do you think if we also add a third timeout option that would basically do what I described in my last comment? Something like an idle_timeout that will fire when the request has started but for some reason is stalled in the middle.
> 
> Example: We have a very large report that downloads fine for 5 seconds, but is then stalled. If we have a deadline timeout of maybe 120 seconds (because we expect a very large file with a long download time) it would only fire after that time, but if we also include an idle timeout of maybe 30 seconds it would fire after 35 seconds already.

I think this would be a useful feature to add. I guess the idle timeout would fire if the response "data" event has not occured for the idle_timeout. I don't know how often the response "data" event fires in normal use - provided the chunks of data are quite small this should work well but it might need some testing.

> And the other idea would be to add the timeout option to the initial class config as well so that its possible to set these values for all calls of a class instance.

This could be a useful addition, but I think support on a per-call basis is necessary as some API calls are likely to be slower than others, depending on how fast Amazon can process them and the amount of data involved.

> And one more idea: Do you think it would make sense if we make a timeout object instead of single values? So to say timeout.response, timeout.deadline and timeout.idle?

Yes, I think this makes sense - I only used separate variables to try to follow the "style" of the library so far, keeping the timeout settings together in a single timeout object seems like a nice clean way to do things.

**Comment by amz-tools** [comment]
Hi @colin-brown,

sorry for missing a reply here. Yeah, feel free to make the changes.

**Comment by wangjue666** [comment]
Quickly use this Feature, you can install 

```
npm i amazon-sp-api-timeout
```

**Comment by colin-brown** [comment]
> Hi @colin-brown,
> 
> sorry for missing a reply here. Yeah, feel free to make the changes.

Thanks - been snowed under recently but will aim to get the changes made in the near future. I will probably not have time to add the timeout option to the initial class config but will try to find time to make the other changes.

**Comment by amz-tools** [comment]
Hi @colin-brown,

I have merged your PR and made the changes discussed earlier:

- Moved options to timeouts object
- added idle timeout as third timeout option
- added possibility to set timeouts global in class constructor config options
- added timeouts option to download

Feel free to check it out and provide a feedback if you find something missing.
