### ISSUE TITLE
Wanting to use this library in firebase functions but can't due to the method of loading config info

### ISSUE THREAD

**Issue by donhmorris** [amz-tools/amazon-sp-api#15]
It would be really helpful to pass in config information via another way instead of using a file or environment variables. These two options will not work for firebase functions since you can't utilize the file system nor environment variables.

**Comment by amz-tools** [comment]
Hi!

we didn't provide a possibility to just pass them in (i.e. inside the constructor config options) because considering the security perspective it probably shouldn't be recommended to hard code the credentials inside the project. Anyway, I think for use cases like yours it would be good to have this option. We wouldn't have to promote inside the Readme, but can still have the option. Will look into it, think we can come up with something here.

**Comment by donhmorris** [comment]
Thanks for considering my situation and looking at my feedback.

I have some additional feedback on the current design for configuration. You mentioned that using environment variables and using a file for configuration was chosen for security reasons. I suggest you switch to passing all config info through the constructor and let the consumer of your library handle security in a way that they deem appropriate. If you make this change it will not prevent developers from still using environment variables or a file to control configuration of the library. It would just move the choice of how to do it to a different level. I really think it should be up to the consumer of the library to make decisions about securing credentials. For example, what if I want to pull my credentials from a db?

I would encourage you to drop the current design of how credentials are set. I know it is a breaking change but the current design seems to make too many assumptions about configuration. 

Having said all that, this looks like a pretty solid library. I appreciate how you guys adopted oop in developing the code.

**Comment by amz-tools** [comment]
We just added an option to pass in the credentials via the constructor config object. The two ways via env vars or config file are still unchanged, so its just another possibility of loading them and as a result there are no breaking changes. Although considering security and convenience (no need to pass credentials in config params to every new instance) we are still fans of the other two options. we think this third option gives everyone the possibilty to use his or her "best way". In fact all the different ways one could choose to load credentials from (i.e. from a db) should be possible with this solution without completely changing the logic.

**Comment by donhmorris** [comment]
Sounds good. Thanks for listening.
