### ISSUE TITLE
Optional 'x-amz-security-token' header is always required

### ISSUE THREAD

**Issue by rmp135** [amz-tools/amazon-sp-api#152]
The header `x-amz-security-token` is always required when signing the request for calling the API (see [Signer.js Ln 132](https://github.com/amz-tools/amazon-sp-api/blob/5109617bab73a3ad46769ad4e12a392d97542938/lib/Signer.js#L132)). 

Because of this I'm unable to use the long-term credentials that don't require this header. I've tried setting `role_credentials.security_token` to empty string and null and in both cases the request fails. Removing the header completely is the only way to get a successful response.

I notice on [Signer.js Ln 165](https://github.com/amz-tools/amazon-sp-api/blob/5109617bab73a3ad46769ad4e12a392d97542938/lib/Signer.js#L165) that the token is only added when it exists. I suspect a similar fix can be applied here.

**Comment by amz-tools** [comment]
Hi @rmp135,

we weren't really aware of the fact that its possible to actually call the API without the `x-amz-security-token`. This isn't documented in the SP API docs, is it? Could you just explain how its working so we have a better understanding of it?

**Comment by rmp135** [comment]
Sure.

On constructing the SellingPartnerAPI, I've set both `AWS_ACCESS_KEY_ID` and `role_credentials.id` to the AWS access key ID and `AWS_SECRET_ACCESS_KEY` and `role_credentials.secret` to the AWS secret access key. Along with the client id and secret.

This allows for the `refreshAccessToken` to successfully return a refresh token. 

On calling orders.getOrders I get `Invalid value "undefined" for header "x-amz-security-token"` which makes sense, it's adding undefined as the value. However, applying the fix above solves this issue as it's no longer attempting to add the token header.

Your [request signing documentation](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) states the following:

"You can use temporary security credentials provided by the AWS Security Token Service (AWS STS) to sign a request. The process is the same as using long-term credentials, but when you add signing information to the query string you must add an additional query parameter for the security token. The parameter name is X-Amz-Security-Token..."

This implies that for additional security you can use the STS token, not that it's required.

**Comment by amz-tools** [comment]
Interesting. So just to understand the flow: You just skip the whole `refreshRoleCredentials()` call, removed the `x-amz-security-token` header and its working? What I am wondering is, then it must be working without specifying an `AWS_SELLING_PARTNER_ROLE` as this role is only used to retrieve the security token…

**Comment by rmp135** [comment]
That's correct, I don't refresh the role credentials and `AWS_SELLING_PARTNER_ROLE` is blank. After removing the token header completely the call responds successfully.

**Comment by amz-tools** [comment]
@rmp135, okay, then I think we should really make it optional (`AWS_SELLING_PARTNER_ROLE` as well) and update the docs accordingly.

**Comment by charmant** [comment]
Hello, @amz-tools are you planing to fix it? I have same problem.

**Comment by amz-tools** [comment]
Hi @charmant,

yes, we are. We are a bit short in time right now in order to introduce new features / enhancements to the client, but we are planning an update that will introduce this and a couple of other features as well (stream mode, timeouts, etc.).

**Comment by amz-tools** [comment]
Published in v0.8.0
