### ISSUE TITLE
Access to requested resource is denied calling getCatalogItem

### ISSUE THREAD

**Issue by mcherubin** [amz-tools/amazon-sp-api#153]
Hi, I have a permissions problem calling the 'getCatalogItem' operation, I have no problems with other operations like 'getMarketplaceParticipations' or 'getOrders'; when I call this function I get

{"message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "", "type": "error"}

This is my code
```
		
                              let sellingPartner = new SellingPartnerAPI({
					region:'eu',
					credentials: {
					    SELLING_PARTNER_APP_CLIENT_ID:'<MY_SELLING_PARTNER_APP_CLIENT_ID>',
					    SELLING_PARTNER_APP_CLIENT_SECRET: '<MY_SELLING_PARTNER_APP_CLIENT_SECRET>',
					    AWS_ACCESS_KEY_ID:'<MY_AWS_ACCESS_KEY_ID>',
					    AWS_SECRET_ACCESS_KEY:'<MY_AWS_SECRET_ACCESS_KEY>',
					    AWS_SELLING_PARTNER_ROLE:'<MY_AWS_SELLING_PARTNER_ROLE>'
					},
					access_token: my_access_token,
					refresh_token: my_refresh_token
				});

				await sellingPartner.refreshAccessToken();		

				let ResItem = await sellingPartner.callAPI({
					operation: 'getCatalogItem',
					endpoint: 'catalogItems',
					path: {
						asin: 'B08F582HWR'
					},
					query: {
					    marketplaceIds: ['APJ6JRA9NG5V4']
					}
				});
```

Has anyone had similar problems?

**Comment by amz-tools** [comment]
Hi @mcherubin,

two possible reasons:

One could be that the account you use doesn't have access to the Italy marketplace (APJ6JRA9NG5V4).

The other reason which I would say is most probably the reason here is the version. When you don't provide a version it uses the oldest version of the endpoint. In this case `v0` of `catalogItems`, which expects a different input. So you might want to add the new version to the options of the call:
```
options:{
  version:'2022-04-01'
}
```

**Comment by mcherubin** [comment]
Thanks for your answer, if I call getMarketplaceParticipations the Italy marketplace is listed.

I've try to add the options value

```
let ResItem = await sellingPartner.callAPI({
	operation: 'getCatalogItem',
	endpoint: 'catalogItems',
	query:{
		marketplaceIds:['APJ6JRA9NG5V4'],
	},
	path:{
		asin:'B08F582HWR'
	},
	options:{
	  version:'2022-04-01'
	}
});
```

But I get the same error :(

**Comment by amz-tools** [comment]
Thats strange, when I try the exact same call I do receive a valid response:
```
{
  asin: 'B08F582HWR',
  summaries: [
    {
      marketplaceId: 'APJ6JRA9NG5V4',
      brand: 'Argentoè',
      browseClassification: { displayName: 'Borracce', classificationId: '3102180031' },
      itemClassification: 'BASE_PRODUCT',
      itemName: 'Argentoè MyBottles Borraccia Antibatterica in Alluminio da 600ml Made in Italy - Sport 600 Classic, Modello Travel',
      manufacturer: 'Argentoè',
      websiteDisplayGroup: 'sports_display_on_website',
      websiteDisplayGroupName: 'Sport'
    }
  ]
}
```

I can see you refresh the access token, maybe try to refresh the role credentials as well:

`await sellingPartner.refreshRoleCredentials();`

**Comment by mcherubin** [comment]
i tried as you suggested refreshRoleCredentials but i have the same error

**Comment by mcherubin** [comment]
Now I try to add any european marketplaces to the query marketplaceIds, and it works. After doing this operation, now it works fine even if I specify only 'APJ6JRA9NG5V4' marketplace. Very strange.

**Comment by amz-tools** [comment]
Indeed strange. So I suppose we can close this issue?

**Comment by mcherubin** [comment]
Yes we can close this issue. I suppose this is a little bug inside the Role validation of Amazon AWS
