### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by ALEXOTANO** [amz-tools/amazon-sp-api#16]
Hello! Is there a way to add sandbox mode?, I've been working on this library for an while but I can't make it work. 

I was adding a boolean sandbox variable in SellingPartner.js, which is passed to Signer.js (only for signing requests not request of credentials) and finally to the request.js , all it does is add "sandbox." string at the begining of the URL, asi in the documentation. 

But I'm getting 

```bash
CustomError: We encountered an internal error. Please try again.
    at SellingPartner.callAPI (/var/www/nodes/oadmin/node_modules/amazon-sp-api/lib/SellingPartner.js:234:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.getOrdersAmazon (/var/www/nodes/oadmin/dist/router-mongo/amazon/amazon.helper.js:152:15)
    at async /var/www/nodes/oadmin/dist/router-mongo/amazon/amazon.helper.js:284:28 {
  code: 'InternalFailure',
  type: 'error'
}
```
Any hints? I was planning to finish this feature and make a PR, seams like a very simple feature but so helpful.

**Comment by amz-tools** [comment]
Hi!

Nice idea! Hard to tell from the error what exactly is wrong, but the error ("encountered internal error") looks like you are calling an operation with invalid parameters. For example if you take a look at the [fba inventory json](https://github.com/amzn/selling-partner-api-models/blob/main/models/fba-inventory-api-model/fbaInventory.json) in the selling partner models and search for "x-amazon-spds-sandbox-behaviors" you can see that passing in an invalid marketplaceID will return exactly the error you encountered.

**Comment by ALEXOTANO** [comment]
ok ok! I'll look into it! thanks for the hint!
