### ISSUE TITLE
Amazon Click&Collect - endpoint "supplySources" 

### ISSUE THREAD

**Issue by Bowserlord** [amz-tools/amazon-sp-api#163]
Hello,

thank you again for the wonderful working nodejs-application.

I just have a short question:
Will the endpoint "supplySources" added in near feature?
This endpoint is needed for Amazon Click&Collect.

Thank you very much and kind regards
Bowser

**Comment by amz-tools** [comment]
Hi @Bowserlord,

to be fully honest with you, we didn't even know this endpoint existed. Its not listed in the docs, is it? It seems its only listed here: [https://developer-docs.amazon.com/sp-api/docs/selling-partner-insights-role#apis](https://developer-docs.amazon.com/sp-api/docs/selling-partner-insights-role#apis)

Or do you have a link to a documentation of that endpoint?

**Comment by amz-tools** [comment]
@Bowserlord Very long time, but its finally included in version 1.1.0 :-)
