### ISSUE TITLE
code: 'AccessDenied',   type: 'error'

### ISSUE THREAD

**Issue by rmajidy** [amz-tools/amazon-sp-api#166]
User: arn:aws:sts::xxxxxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxx

` at SellingPartner.refreshRoleCredentials (/Users/me/repos/npm-amazon-sp-api/node_modules/amazon-sp-api/lib/SellingPartner.js:521:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SellingPartner._validateAccessTokenAndRoleCredentials (/Users/me/repos/npm-amazon-sp-api/node_modules/amazon-sp-api/lib/SellingPartner.js:291:9)
    at async SellingPartner.callAPI (/Users/me/repos/npm-amazon-sp-api/node_modules/amazon-sp-api/lib/SellingPartner.js:574:5)
    at async /Users/me/repos/npm-amazon-sp-api/index.js:10:17 {
  code: 'AccessDenied',
  type: 'error'
}`

I'm new to AWS and man it's really a pain to setup just for just a simple API request. I used the aws cli to generate the temporary security credentials with the AWS cli (seen below)

`aws sts assume-role --role-arn arn:aws:iam::123456789012:role/role-name --role-session-name "RoleSession1" --profile IAM-user-name > assume-role-output.txt`

Once it generated the assume-role-output.txt I then added the `AWS_SELLING_PARTNER_ACCESS_KEY_ID` `AWS_SELLING_PARTNER_SECRET_ACCESS_KEY` and `AWS_SELLING_PARTNER_SESSION_TOKEN` to the new env file while.

I also hard coded the `refresh_token`  on the client side. 

If anyone could help me that would be amazing. I got it working the the python api but would like to use js to build out my application. Thanks for any help!

**Comment by amz-tools** [comment]
As STS is not required anymore we can close this issue.
