### ISSUE TITLE
Access to requested resource is denied. When using IAM user in registration process

### ISSUE THREAD

**Issue by nabeelasjid1** [amz-tools/amazon-sp-api#175]
I am having this issue for the last 3 days,
From the postman, When I don't assume role, all the APIs work well,
but after assuming the role, I get `Access to requested resource is denied.` Error.

Now because this Library auto assumes the role, so I am getting the above error, and am unable to solve it.

Possible reasons for this is: 
The client registered application with `IAM user` instead of `IAM role` and I'm stuck here.

Anyone can help me??

**Comment by arorasahil1209** [comment]
same here , have you found a solution?

**Comment by nabeelasjid1** [comment]
I simply go to the SP API application on the developer portal on amazon seller central, and change `IAM Role`  with  `IAM User`.

**Comment by born2net** [comment]
same here... any solution?

**Comment by amz-tools** [comment]
Closed as wontfix/invalid as signing is not necessary anymore.
