### ISSUE TITLE
Financial events filtered by marketplace

### ISSUE THREAD

**Issue by bry221996** [amz-tools/amazon-sp-api#177]
Is there a way to filter financialEvents by marketplace ? 

 https://developer-docs.amazon.com/sp-api/docs/finances-api-reference  
 
 Need to identify which financial events happen in specific marketplace. thanks

**Comment by amz-tools** [comment]
Hi @bry221996,

thats not possible as the finances also includes events that are not marketplace specific, i.e. the professional seller account fee amongst others. However marketplace specific events usually also return the marketplace id, so you should be able to assign the values to the right marketplace for the events where its possible.
