### ISSUE TITLE
Is there any API to retrieve inbound shipment discrepancies/investigation?

### ISSUE THREAD

**Issue by phstc** [amz-tools/amazon-sp-api#184]
Sorry, probably not the best place to ask! 

Is there any API to get statutes for discrepancies/investigation?

I'm already using the [shipments and shipment items API](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference), but they don't return discrepancies/investigation info.

![image](https://user-images.githubusercontent.com/105652/213002536-e54cf681-b5d4-43a7-9d62-37822e141b18.png)

**Comment by amz-tools** [comment]
@phstc I don't think there is a direct way to do it, but you should be able to check how many items were sent to Amazon and what the final received items amount is once the shipment is in status closed. The difference should then give you the missing items.

**Comment by phstc** [comment]
@amz-tools that makes sense. I was wondering if there's a way if there's a case opened already for an FBA Reimbursement. But I couldn't find any API for that or for creating cases through the API.

Do you know if there's any API for cases (listing or creating)?

**Comment by amz-tools** [comment]
@phstc No, there is no endpoint to open cases or retrieve them via the API.

**Comment by phstc** [comment]
@amz-tools thank you! That's what I thought. I've seen some apps doing it, but I'm guessing they use bots.
