### ISSUE TITLE
[Shipping v2] By any chance we can get the Shipping v2 APIs integrated?

### ISSUE THREAD

**Issue by abhishek-hopstack** [amz-tools/amazon-sp-api#186]
link: https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference

**Comment by amz-tools** [comment]
@abhishek-hopstack Yes, we will release a new version within the next week, this will also include Shipping v2.

**Comment by Roman991** [comment]
> @abhishek-hopstack Yes, we will release a new version within the next week, this will also include Shipping v2.

This update will be a feature release or a major refresh?
Cuz i'm reviewing the TS part, and currentry its a complete mess

**Comment by amz-tools** [comment]
@Roman991 This will be just a feature release, but we are planning to release a new major version 1.x some time in the future with a much better TypeScript support. However not quite sure when we will find the time to do so.

**Comment by Roman991** [comment]
> @Roman991 This will be just a feature release, but we are planning to release a new major version 1.x some time in the future with a much better TypeScript support. However not quite sure when we will find the time to do so.

would u consider a complete revamp of the declaration lib? or maybe just give me the guidelines of how you want that

**Comment by abhishek-hopstack** [comment]
> @abhishek-hopstack Yes, we will release a new version within the next week, this will also include Shipping v2.

Thanks @amz-tools, looking forward for the update. If possible, can you please give an ETA ?

**Comment by amz-tools** [comment]
Hi @abhishek-hopstack,

sorry for the late reply, we just released version 0.8.1 that includes Shipping v2 endpoint.

**Comment by amz-tools** [comment]
@Roman991 Yes, definitely planing to do it fully new. We have not discussed in detail how we want to set it up though.
