### ISSUE TITLE
How to retrieve the Request ID?

### ISSUE THREAD

**Issue by phstc** [amz-tools/amazon-sp-api#187]
I have a support issue with Amazon, and they are asking me for the Request ID available in the response. But I could not find it in the response. How can I retrieve the Request ID? I've tried to enable `debug_log` but it does not log that out. 

> To investigate further, please provide the following details:
> 
>    - Developer ID for the software/application/interface being used to submit the request
>    - The Request ID (available in the response)

**Comment by amz-tools** [comment]
@phstc Yes, thats pretty easy. You can pass `raw_result:true` inside the `options` of `.callAPI()`. This will return the raw result including the response headers that will include the request id.

**Comment by phstc** [comment]
@amz-tools thank you! That's very helpful.
