### ISSUE TITLE
getReports call returns 503 error half of the time

### ISSUE THREAD

**Issue by aminakhyat** [amz-tools/amazon-sp-api#195]
I'm currently using the Amazon Selling Partner API library for Node.js to retrieve all reports of type GET_MERCHANT_LISTINGS_ALL_DATA. However, I'm consistently receiving a 503 error when making the API call, even though I'm passing in filters that should limit the number of records returned.

The client is created correctly because this is the only call failing and returning this. 

Here's the relevant code snippet I'm using:
```
const reports = await client.callAPI({
    operation: 'getReports',
    endpoint: 'reports',
    query: {
      reportTypes: [reportType],
      marketplaceIds: [marketplaceId],
      processingStatuses: [REPORT_PROCESSING_STATUS_DONE],
      pageSize: 100,
      createdSince: '2023-03-19'
    },
    path: {}
  })
```

Please let me know if you need any additional information or if there's anything I can do to help troubleshoot this issue.

**Comment by amz-tools** [comment]
@aminakhyat Thats quite strange. According to Amazon they define 503 status as "Temporary overloading or maintenance of the server." So probably nothing is wrong with your input. Maybe its a version issue? You could try to set the new version of reports endpoint as option if you don't do that yet, like so:
```
const reports = await client.callAPI({
    operation: 'getReports',
    endpoint: 'reports',
    query: {
      reportTypes: [reportType],
      marketplaceIds: [marketplaceId],
      processingStatuses: [REPORT_PROCESSING_STATUS_DONE],
      pageSize: 100,
      createdSince: '2023-03-19'
    },
    options: {
      version: '2021-06-30'
    }
});
```
