### ISSUE TITLE
Missing operation confirmShipment.orders

### ISSUE THREAD

**Issue by yonahochieng** [amz-tools/amazon-sp-api#199]
![image](https://user-images.githubusercontent.com/5019807/230207199-2e130a8d-c03c-4691-8ef5-f4d7047f6c42.png)

**Comment by yonahochieng** [comment]
Currently using
`let res = await sellingPartner.callAPI({
    //operation: 'confirmShipment',
    //endpoint: 'orders',
    api_path:`/orders/v0/orders/${order_id}/shipmentConfirmation`,
    method:'POST',
    // path: {
    //   orderId: '902-1106328-1059050'//order_id
    // },
    body: {
      packageDetail: {
        packageReferenceId: '1',
        carrierCode: 'FedEx',
        "carrierName": "FedEx",
        "shippingMethod": "FedEx Ground",
        trackingNumber: '112345678',
        shipDate: '2022-02-11T01:00:00.000Z',
        //orderItems: items
        "orderItems": [
          {
            "orderItemId": "79039765272157",
            "quantity": 1,
            "transparencyCodes": [
              "09876543211234567890"
            ]
          }
        ]

      },
      marketplaceId: marketplace_id
    }
  });`

**Comment by amz-tools** [comment]
@yonahochieng We merged your PR concerning this issue into new version v0.8.4.
