### ISSUE TITLE
Operation 'getMyFeesEstimateForASIN' has wrong URI

### ISSUE THREAD

**Issue by ChrisSnake** [amz-tools/amazon-sp-api#2]
Hi,

thanks for your great work. It helped a lot.

I think, for operation 'getMyFeesEstimateForASIN' there is a wrong URI.
In lib/resources/productFees.js, you wrote 

https://github.com/amz-tools/amazon-sp-api/blob/ef67c2f6550ab3feec6a2710c664075f71f25e88/lib/resources/productFees.js#L50

But according to documentation, api_path should be: 
```JS
api_path: '/products/fees/v0/items/' + req_params.path.Asin + '/feesEstimate'
```

Would be great to fix that, thanks.

**Comment by amz-tools** [comment]
Hi,

thank you, you are absolutely right. Just fixed the path and published.
