### ISSUE TITLE
includedData returns signature error

### ISSUE THREAD

**Issue by Philomath88** [amz-tools/amazon-sp-api#201]
Hi,

this is our function: 

`const getCatalogItemDetails = async (asin) => {
  try {
    const response = await sellingPartner.callAPI({
      operation: 'catalogItems.getCatalogItem',
      path: {
        asin: asin,
      },
      query: {
        MarketplaceId: 'A1PA6795UKMFR9', // Replace this with your desired marketplace ID
        //includedData: encodeURIComponent('ALL'),
        includedData: ['attributes', 'dimensions', 'identifiers', 'productTypes', 'relationships', 'salesRanks', 'summaries', 'vendorDetails'].join(','),
      },
    });
    console.log(response);
  } catch (error) {
    console.error(error);
  }
};`

But it returns the following error:

CustomError: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.The Canonical String for this request should have been'GET/catalog/v0/items/B09ZB5GXF1MarketplaceId=A1PA6795UKMFR9&includedData=attributes%2Cdimensions%2Cidentifiers%2CproductTypes%2Crelationships%2CsalesRanks%2Csummaries%2CvendorDetailshost:sellingpartnerapi-eu.amazon.comuser-agent:amazon-sp-api/0.6.6 (Language=Node.js/v18.16.0; Platform=Darwin/22.3.0)x-amz-access-token:Atza|IwEBIG4H0_5bfawWYs_nqfGW-DOc0bft3eGxOKflPc-wkNx14DS-H4NYFTTaOXlaOdGqETCXRGJBG1eSVZFUjqVUEtFBQCDjpwb1UKi7pCCRzrUN-_38vINfXiTvIkNX-siy5ffTbR8nuSoCpiiPI-EoD_OwpBDb8NO_TDPxoYdls7e13DOPq85ihkMMP26XVsgVt8S7uHBkT8-nIxg0KgzhTv_F4rpCEx_bAjFm5-bMFjDd2ocTiQBcY36KfLqznq0yQJp6j8ZRTAcjYzIwgkw91IY8rtGnvb7F3ynSHAzgZHKRDKORUqJoruWtPMt7y31BnlW2O3lJ8RRciqKW4WqpL6QlNGgqoHgdRs5E4t6jwBPelwx-amz-date:20230419T092654Zhost;user-agent;x-amz-access-token;x-amz-datee3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'The String-to-Sign should have been'AWS4-HMAC-SHA25620230419T092654Z20230419/eu-west-1/execute-api/aws4_request45a167c28d22408eedbd4bd95ae6ca947d93c979a00c6d3cbe8ee66f58e076fa'

It works fine if we don't add the includedData property.

**Comment by amz-tools** [comment]
Closed as wontfix/invalid as signing is not necessary anymore.
