### ISSUE TITLE
debug_log

### ISSUE THREAD

**Issue by chengkiang** [amz-tools/amazon-sp-api#204]
When I turn enable debug_log, only see a console message 

```
Loaded credentials from config object
```

Is it possible to show the request and response data in debug mode as well?

Regards
CK

**Comment by amz-tools** [comment]
@chengkiang For the response data you can add `raw_result:true` to the options when you use .`callAPI()`. This will return the raw result including response headers etc.

**Comment by chengkiang** [comment]
> @chengkiang For the response data you can add `raw_result:true` to the options when you use .`callAPI()`. This will return the raw result including response headers etc.

Great, that works. Is there a way to see the request data as well? This will be useful when contacting SP-API support and they ask what for it.

Thanks!

Regards
CK

**Comment by amz-tools** [comment]
@chengkiang Not yet I am afraid. You could however add a `console.log` when `debug_log` is `true` for the request params and open a PR.

**Comment by amz-tools** [comment]
@chengkiang We now added a request log when setting `debug_log` to `true`.
