### ISSUE TITLE
New ORDER_CHANGE notificationType bug

### ISSUE THREAD

**Issue by lacherogwu** [amz-tools/amazon-sp-api#221]
You've just announced about new notification type & the old notification type will be depracated
https://github.com/amzn/selling-partner-api-docs/discussions/3201

and it's mentioned everywhere in your docs as well that `notificationType: ORDER_CHANGE` is not available and going to replace `ORDER_STATUS_CHANGE`

but unfortunately it doesn't work

```js
spApi.callAPI({
	operation: 'notifications.createSubscription',
	body: {
		payloadVersion: '1.0',
		destinationId: 'xxx',
	},
	path: {
		notificationType: 'ORDER_CHANGE',
	},
});
```

but I'm getting this error
`CustomError: Invalid value "ORDER_CHANGE" for path parameter notificationType`

**Comment by lacherogwu** [comment]
NVM, I see now that it's not the official aws library and some new things my not be supported yet, anyway thanks for your great client, helps a lot!

**Comment by dlamb22** [comment]
Any idea when this will be available?
