### ISSUE TITLE
"submitFulfillmentOrderStatusUpdate"operation is missing

### ISSUE THREAD

**Issue by stockjoints** [amz-tools/amazon-sp-api#223]
While trying to implement simple sandbox flow i encountered `submitFulfillmentOrderStatusUpdate` of `fulfillmentOutbound.` being unavailable.
`err: {
      "type": "Error",
      "message": "No operation found: submitFulfillmentOrderStatusUpdate",
      "stack":
          Error: No operation found: submitFulfillmentOrderStatusUpdate
...`
`v0.8.3`

**Comment by amz-tools** [comment]
@stockjoints `submitFulfillmentOrderStatusUpdate` has been added to the newly released version v0.8.4
