### ISSUE TITLE
nextToken not being sent via getReports

### ISSUE THREAD

**Issue by max0783** [amz-tools/amazon-sp-api#226]
I have the following piece of code to retreive settlement reports:

```
async function getReports(reportTypes, marketplaceIds = ["ATVPDKIKX0DER"], nextToken = null) {
  try {
    let query = {
      reportTypes,
      marketplaceIds,
      pageSize : 20 //later increased to 100
    };

    if (nextToken) {
      query.nextToken = nextToken;
    }

    let reportData = await sp.callAPI({
      operation: "getReports",
      endpoint: "reports",
      query: query,
    });
    console.log(reportData)
    // If there's a NextToken, recursively call this function to get more reports
    if (reportData.NextToken) {
      let additionalReports = await getReports(reportTypes, marketplaceIds, reportData.NextToken);
      // Combine the current report data with the additional reports
      reportData.reports = reportData.reports.concat(additionalReports.reports);
    }

    return reportData;
  } catch (e) {
    logger.error(e);
  }
}
```

When I do this, and at least only tried this while I'm asking for settlement reports, no nextToken is provided.

The call looks like this 

`await getReports("GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2");`

however, after checking the console.log with the response, no nextToken was sent, and then I increased the page size to 100, and there were indeed more settlement reports to be downloaded. I cannot access any of the rest of the 100. 

Any idea if this may be Amazon's mistake?

**Comment by sean-moser** [comment]
As much as I like to blame Amazon as well, this is actually an issue with amazon-sp-api.  I have made a pr fixing the issue https://github.com/amz-tools/amazon-sp-api/pull/239

**Comment by sean-moser** [comment]
So as somebody pointed out to me this was an issue with the 2020-09-04 endpoint.  The v2021-06-30 endpoint does correctly return the nextToken in the payload.  The v2020-09-04 endpoint will stop working on 18th October 2023 so it is best to start using the new endpoint.
