### ISSUE TITLE
SKU encoded by amazon API result 

### ISSUE THREAD

**Issue by baltechies** [amz-tools/amazon-sp-api#232]
Hi, I am using SP Report API to get listing data. I am using GET_MERCHANT_LISTINGS_ALL_DATA.
In response its returning data, but SKU is encoded. Its return sku as Cr�me and Jalape�o. But actual SKUs are like Crème  and Jalapeño.

Can you please suggest how can I convert it back to Crème and Jalapeño?

**Comment by amz-tools** [comment]
@baltechies This is probably due to a wrong charset, please have a look at the docs and search for `GET_MERCHANT_LISTINGS_ALL_DATA`.

Providing the right charset should solve your issue:
```
let report = await spClient.download(report_document, {
 charset:'cp1252' 
});
```
