### ISSUE TITLE
Cannot find type definition file for 'operations'

### ISSUE THREAD

**Issue by mpenna** [amz-tools/amazon-sp-api#235]
I'm using this lib inside a Nestjs API project and I continuously get this error/problem message on VS Code's console: 

```txt
Cannot find type definition file for 'operations'.
  The file is in the program because:
    Entry point for implicit type library 'operations'
```

Any idea why?

**Comment by martinArg96** [comment]
i resolved with: 
npm update amazon-sp-api

then i reset vscode
