### ISSUE TITLE
"Could not match input arguments" Issue in calling "createReport" api

### ISSUE THREAD

**Issue by kjeih** [amz-tools/amazon-sp-api#236]
```
const res = await sp.callAPI({
      operation: "reports.createReport",
      body: {
        reportType: "GET_FBA_MYI_ALL_INVENTORY_DATA",
        marketplaceIds: [MARKETPLACE_ID],
      },
    });
```
**Response:** 
_CustomError: Could not match input arguments_

before calling this, I checked authorization with the following code.
```
await sp.callAPI({ operation: "getMarketplaceParticipations" })
```
This is working well and returns right data.

What am I wrong?

**Comment by amz-tools** [comment]
@kjeih When I try your call it works fine when adding a valid marketplace id. Maybe the account you are generating the report for is not an FBA seller or is a vendor account?

**Comment by kjeih** [comment]
I am sure I used FBA seller.
Api is successing when calling "getMarketplaceParticipations". But reports and catalogItem endpoints are not working.
What is the issue.

**Comment by kjeih** [comment]
@amz-tools I found the issue.
When creating sellerApiClient, I used the wrong basepath (sandbox url).

Thanks for your kindly response.
I will close this issue.
Thanks.
