### ISSUE TITLE
TypeError: SellingPartner.downloadReport is not a function.

### ISSUE THREAD

**Issue by dvdgaming** [amz-tools/amazon-sp-api#240]
Got all of our credentials / iam users / policies and roles working.
(and I can use the sample code to "request a report" which works as I can see the report being generated on our amazon account)

when i run the sample downloadReport code from the readme file,
I get 
TypeError: SellingPartner.downloadReport is not a function.

What I am doing wrong,
Apologies in advance (really new to Javascript)

Nick
 ----

let res = await SellingPartner.downloadReport({
  body:{
    reportType:'GET_FLAT_FILE_OPEN_LISTINGS_DATA',
    marketplaceIds:['A1F83G8C2ARO7P']
  },
  version:'2021-06-30',
  interval:8000,
  download:{
    json:true,
    file:'<ABSOLUTE_FILE_PATH>/report.json'
  }
});

**Comment by dvdgaming** [comment]
Ah! - Solved it
I should have used 
let res=await spClient  . . . .
and not
let res=await SellingPartner . . . . . 

SellingPartner was already used elsewhere in the script hence the typeerror

**Comment by jagdish-kc** [comment]
const spClient = new SellingPartner({
        region: region,
        refresh_token: refreshToken,
        credentials: {
          SELLING_PARTNER_APP_CLIENT_ID: appClientID,
          SELLING_PARTNER_APP_CLIENT_SECRET: appClientSecret,
        },
      })

      const response = await spClient.downloadReport({
        body: {
          reportType: 'GET_MERCHANT_LISTINGS_ALL_DATA', //"GET_FLAT_FILE_OPEN_LISTINGS_DATA",
          marketplaceIds: [marketplaceId], //['A1PA6795UKMFR9'], // for spain
        },
        version: '2021-06-30',
        interval: 5000,
        download: {
          json: true,
          file:
            './Api-Reports/Listing/Listing-' +
            '_' +
            new Date().toISOString().replace(/:/g, '_').replace(/\..+/, '').replace(/T/, '_') +
            '.json',
        },
      })
      
      
      I am also getting same error. What the issue?

**Comment by dvdgaming** [comment]
what error message you getting?

**Comment by jagdish-kc** [comment]
downloadReport is not a function.

**Comment by dvdgaming** [comment]
just downloadReport is not a function or is there a prefix to downloadReport on the error message

such as 

somethingelse.downloadReport is not  a function
