### ISSUE TITLE
`updateFulfillmentOrder` incorrect method

### ISSUE THREAD

**Issue by stockjoints** [amz-tools/amazon-sp-api#242]
`updateFulfillmentOrder` of `fulfillment_outbound` incorrectly uses `GET` instead of `PUT`, and call throws. With `PUT` it responds correctly.
`/resources/versions/fulfillment_outbound/fulfillmentOutbound_2020-07-01.js`
`v0.8.4`

**Comment by amz-tools** [comment]
@stockjoints You are right, thats a bug. We will fix this in the next version.
