### ISSUE TITLE
Invalid value "LISTINGS_ITEM_MFN_QUANTITY_CHANGE" for path parameter notificationType

### ISSUE THREAD

**Issue by SWengineer-A** [amz-tools/amazon-sp-api#247]
When I create subscription, I faced bellow issue. 

`Invalid value "LISTINGS_ITEM_MFN_QUANTITY_CHANGE" for path parameter notificationType`

It seems like this notification type need to be added in notifications list.

**Comment by amz-tools** [comment]
@SWengineer-A You are right, its missing. We will add this to the next version.

**Comment by SWengineer-A** [comment]
thanks, @amz-tools 
Looking forward update soon.

**Comment by amz-tools** [comment]
@SWengineer-A Sorry for the late reply. We will release a new version by next week, which will also remove AWS4 signing, as its not needed anymore.

**Comment by amz-tools** [comment]
@SWengineer-A Just released new version 1.0.0 that includes a valid notification types.
