### ISSUE TITLE
How to use it with typescript?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [amz-tools/amazon-sp-api#25]
I saw it has type declaration files in lib/typings, but I'm still getting `Cannot find module 'amazon-sp-api' or its corresponding type declarations.ts(2307)`. 
```
    "amazon-sp-api": "^0.3.5",
```

**Comment by amz-tools** [comment]
@dlaudate-embark Maybe you can help out?

**Comment by nohara-embark** [comment]
@xiaoyu-tamu Could you send over your TSconfig file? Not totally sure but it might be something there

**Comment by dlaudate-embark** [comment]
May also be helpful to know what version of TS you are using. We are a bit behind on TypeScript for the project we used this in (3.7.2).

**Comment by xiaoyu-tamu** [comment]
```
    "typescript": "4.2.3"
    "amazon-sp-api": "0.3.5"
```

```json
// tsconfig
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "strict": true,
    "resolveJsonModule": true,
    "lib": ["ESNext", "DOM"],
    "noEmit": true,
    "sourceMap": true,
    "baseUrl": "./",
    "strictPropertyInitialization": false,
    "incremental": true,
    "esModuleInterop": true,
    "typeRoots": ["./node_modules/@types", "./typings"]
  },
  "exclude": ["node_modules", "dist"]
}
```

**Comment by dlaudate-embark** [comment]
I created a new project with just the base libraries and was able to reproduce the error. Looks like the types aren't being mapped correctly. I think it's because the `index.d.ts` file is inside a directory and not at the root of the project. We can try and open up a PR that fixes this when we have some downtime from our day to day work.

**Comment by paulolramos** [comment]
@dlaudate-embark, moving the `index.d.ts` file to the root directory worked. can we open a PR to correct this issue?

**Comment by dlaudate-embark** [comment]
@paulolramos I don't have access to approve and merge PRs here but if you want to open up a PR, I will absolutely soft approve it. I can also open up that PR if you are unable. Let me know.
