### ISSUE TITLE
Issue of "Access to requested resource is denied."

### ISSUE THREAD

**Issue by vairamuthu1414** [amz-tools/amazon-sp-api#251]
I have completed my authorization process and I have the all Auth details such as the Access token, Refresh token, STS details and LWA details.

When I try to Get the Item details using the below API

GET: {{host}}/catalog/2022-04-01/items?marketplaceIds={{marketplaceid}}

I always get the below response - 403 Forbidden

```
{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}
```

I used the I AM role ARN.

Does any one have idea to resolve this issue?

**Comment by amz-tools** [comment]
@vairamuthu1414 Amazon has recently removed the necessity of STS token and IAM role. So basically all you need is a `refresh_token`, `SELLING_PARTNER_APP_CLIENT_ID`, and `SELLING_PARTNER_APP_CLIENT_SECRET`. 
You should try to use the new 1.0.0 version and see if the error still persists.

**Comment by vairamuthu1414** [comment]
@amz-tools 
Thank you for your response.
Where can I find the new version of the API document? 
Can u kindly help to find the new version of the Auth steps?

**Comment by amz-tools** [comment]
@vairamuthu1414 Just read the docs of our client, it should be quite self-explanatory. Amazon has also updated the docs on their side as well.

**Comment by vairamuthu1414** [comment]
@amz-tools 
Do you mean the Amazon SP-API document?

**Comment by vairamuthu1414** [comment]
@amz-tools 
I already  checked the Document [](https://developer-docs.amazon.com/sp-api/docs/authorization-errors)

I couldn't find the reason

**Comment by vairamuthu1414** [comment]
@amz-tools 
![Uploading 2023-11-09_18-25.png…]()

**Comment by vairamuthu1414** [comment]
![2023-11-09_18-25](https://github.com/amz-tools/amazon-sp-api/assets/99784041/a15af646-13ce-4c50-9b68-f80420446117)



@amz-tools

**Comment by amz-tools** [comment]
You can try the request directly with the npm module and see if it still fails.

**Comment by vairamuthu1414** [comment]
@amz-tools 
Actually, We are going to use this within SuiteScript(JS). So now trying with the Postman.

If used the No Auth also, I got the same response 403

**Comment by vairamuthu1414** [comment]
@amz-tools 
Is this related the any permission Issue?

If yes what is the permission need for using the ListingItems?

**Comment by vairamuthu1414** [comment]
@igrybkov

**Comment by amz-tools** [comment]
@vairamuthu1414 Your app needs to have the Product Listing Role enabled (https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api)

**Comment by vairamuthu1414** [comment]
@amz-tools 
Thank you  I will check.

**Comment by vairamuthu1414** [comment]
@amz-tools 
The Product Listing Role was enabled on my Developer APP. However, I got the same response (403).
Is there anything to check from my end?

**Comment by vairamuthu1414** [comment]
@igrybkov @erayalakese @zirkelc 
Kindly help me to resolve this issue.

**Comment by zirkelc** [comment]
@vairamuthu1414 it's been a long time since I used the SP-API and I don't have access to one at the moment, so can't really help you with that. Sorry :-/

**Comment by ALEXOTANO** [comment]
@vairamuthu1414 Same here, its been a while, I fixed something to improve support but not actively supporting this.

**Comment by vairamuthu1414** [comment]
Thank you for your assistance. I resolved the issue by reauthorizing my developer app.
