### ISSUE TITLE
TS exception

### ISSUE THREAD

**Issue by AndreyZatserklaniy** [amz-tools/amazon-sp-api#252]
node_modules/amazon-sp-api/lib/typings/index.d.ts:6:3 - error TS2724: '"./operations/orders"' has no exported member named 'GetOrderItemResponse'. Did you mean 'GetOrderItemsResponse'?

**Comment by vincent-clean** [comment]
@amz-tools , same issue for me. 
As I check the sp-api document, there is no type definition for `GetOrderItemResponse`. 
![image](https://github.com/amz-tools/amazon-sp-api/assets/150730588/9eb9d28b-74ad-46a1-876a-13892aaf09fb)
