### ISSUE TITLE
missing productPricing.getCompetitiveSummary from 2022-05-01 version

### ISSUE THREAD

**Issue by ericblade** [amz-tools/amazon-sp-api#254]
https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-reference#getcompetitivesummary

looks like this function is missing from the API internally here.  

also while just reviewing this whole new api section, i tried making a call to getFeaturedOfferExpectedPriceBatch and that just returns "Unauthorized" ..  good lord, the documentation for this api version is a mess.

**Comment by TenUchikawa** [comment]
I'm also got "Unauthorized" issue

**Comment by ericblade** [comment]
to wit, i was complaining about Amazon's documentation, clearly they aren't capable of providing enough information to be able to use many of the functions, and have absolutely no idea what some of them would even be used for.

**Comment by amz-tools** [comment]
@ericblade Added in version 1.0.1

**Comment by ericblade** [comment]
Thank you so much! <3
