### ISSUE TITLE
How can I best get the requestID and timestamp for SP-API support?

### ISSUE THREAD

**Issue by Philomath88** [amz-tools/amazon-sp-api#255]
I submitted a question and got this response: 

My name is Bryan, from the Selling Partner API Developer Support team.

Thank you for the information provided however we are still missing the information below in order to search for the root cause of the issue.

Request ID and timestamp.

I am leaving the case open waiting for your reply

Not sure how to get the requested information

**Comment by amz-tools** [comment]
@Philomath88 The easiest way is to add `raw_result:true` to the `options` object when using `.callAPI`. This will return the raw result of the request including the headers where you should find both the Request ID and the timestamp.
