### ISSUE TITLE
Gracefully handle timeouts

### ISSUE THREAD

**Issue by jakeleventhal** [amz-tools/amazon-sp-api#258]
<img width="1041" alt="Screenshot 2023-12-05 at 9 14 17 AM" src="https://github.com/amz-tools/amazon-sp-api/assets/15133828/456591c7-0d43-4347-b628-ec8fd06ee421">
Timeouts should be gracefully handled and retried

**Comment by amz-tools** [comment]
@jakeleventhal Yes, we also noticed that in the last two weeks there has been an increased number of ETIMEDOUT errors by Amazon. We will try to include a retry handling this week.

**Comment by amz-tools** [comment]
@jakeleventhal We added a retry handling for ETIMEDOUT errors in 1.0.1, please check. You can however still have the client fire the error instead of retrying by setting new config option `retry_remote_timeout` to `false`, but it defaults to `true`.

**Comment by jakeleventhal** [comment]
Sounds good. Probably good to close this issue then

**Comment by amz-tools** [comment]
@jakeleventhal Appears it wasn't finally fixed, however now 1.0.2 was published and is handled correct now. We also added handling of ENOTFOUND in the same way, as from time to time this has become an issue as well.
