### ISSUE TITLE
Credentials variables 

### ISSUE THREAD

**Issue by matteoquintero** [amz-tools/amazon-sp-api#267]
I would like to understand why the configuration does not include these variables
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SELLING_PARTNER_ROLE

**Comment by amz-tools** [comment]
@matteoquintero 

These are not needed anymore due to a change announced by Amazon in September 2023: 
https://developer-docs.amazon.com/sp-api/changelog/sp-api-will-no-longer-require-aws-iam-or-aws-signature-version-4

**Comment by matteoquintero** [comment]
@amz-tools Thank you very much for sharing this information, I did not know it.
