### ISSUE TITLE
Saving GET_LEDGER_SUMMARY_VIEW_DATA report into database 

### ISSUE THREAD

**Issue by rahulserver** [amz-tools/amazon-sp-api#274]
I am trying to save the json array returned by call to GET_LEDGER_SUMMARY_VIEW_DATA aggregated by DAILY and FC
The problem i face is in identifying the primary key because I can not find out any unique combination of attributes. 

So whats the way to store this report data into a sql table?

**Comment by amz-tools** [comment]
@rahulserver I don't think this is a question that should be answered here as it has nothing to do with the amazon sp api itself. Probably rather a question for Stackoverlfow.

**Comment by rahulserver** [comment]
Thanks for the timely response @amz-tools
