### ISSUE TITLE
download report returns empty array when json: true with some reports.

### ISSUE THREAD

**Issue by DoctorWhich** [amz-tools/amazon-sp-api#28]
I am attempting to download a "GET_MERCHANT_LISTINGS_DATA_LITE" report, using SellingPartner.download(). The download succeeds and returns a tab delimited filed when passing no options object, or when {json: false}. When passing {json: true}, the function returns only '[]'. This does not happen for all reports, for example "GET_FLAT_FILE_OPEN_LISTINGS_DATA" reports download perfectly.

**Comment by amz-tools** [comment]
Hi @DoctorWhich,

just tried the report myself, can't confirm the problem. The report returns the same data with and without `json:true` for me. Whats strange though is that it apparently only returns SKUs with stock > 0 that are FBM. FBA SKUs seems to be inlcuded. Can you confirm that?

**Comment by DoctorWhich** [comment]
Ah, well, now that you mention it and I take a closer look at what it's actually putting out I see that the file it returns to me only contains the column headers and no data - in other words it's an empty table, which would explain why it was empty as a JSON. I presume because I'm only selling FBA items and nothing FBM. So if you meant to say excluded rather than included, then I can confirm. Otherwise I can't.

**Comment by amz-tools** [comment]
Ok, thats good to hear. Sorry for the typo, you're right, I meant excluded. So it seems the report works as expected and we can close this issue?

**Comment by DoctorWhich** [comment]
Sure, my mistake.
