### ISSUE TITLE
Can't find name type

### ISSUE THREAD

**Issue by sw-engineer-a** [amz-tools/amazon-sp-api#285]
@amz-tools  After upgrading to 1.1.0, I am facing this issue. 
![image](https://github.com/user-attachments/assets/82087830-e268-44a2-ba43-d4c991758962)

Is there any solution for this?

**Comment by Dmaitri** [comment]
me too. were you able to fix the issue?

**Comment by amz-tools** [comment]
@sw-engineer-a @Dmaitri We have now deleted all the types as the smallAndLight endpoint had previously already been deleted at it is deprecated (Amazon has stopped the Small and Light Program).
