### ISSUE TITLE
Add getAccount operation of sellers API

### ISSUE THREAD

**Issue by jesusvalle** [amz-tools/amazon-sp-api#288]
Could you please add support for the new sellers endpoint call called: 'getAccount'?

Thank you very much.

https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference#getaccount

**Comment by amz-tools** [comment]
@jesusvalle Added it. But please note that it is only available for sandbox and in EU region: https://developer-docs.amazon.com/sp-api/docs/sellers-api-v2024-07-14-use-case-guide
