### ISSUE TITLE
Create Solicitation API Issue

### ISSUE THREAD

**Issue by sheshankdebugged** [amz-tools/amazon-sp-api#29]
Hi 
I am working on create Solicitation API , But it provide me Error that marketplaceIds is missing or invalid,
When I check the code of npm repository I saw the marketplaceIds  is not added in API route ,
We are able to create Solicitation by postman . The Example of request URL is 
https://sellingpartnerapi-eu.amazon.com/solicitations/v1/orders/{orderId}/solicitations/productReviewAndSellerFeedback?marketplaceIds={marketpalaceId}
And After adding marketpalaceId  in node module of amazon-sp-api in Create Solicitation the Error Changes to 
The request signature we calculated does not match the signature you provided.
But by postman we are able to create Solicitation with same AWS credentials.

**Comment by amz-tools** [comment]
Hi @sheshankdebugged ,

the object with api_path and method is assigned to the parameters object you pass in to the operation and then later in the Signer class the query params are added to the path as a querystring, so in your case "marketplaceIds" and its value is added to the querystring and from there passed on to the request itself.

I just tried the call, it seems to work fine. I can call the operation with the amazonOrderId and the corresponding marketplaceId. It returns a 201 status as expected and when I try the same call again it gives me the message "You have already requested a review for this order.", which also seems to be correct.

This is the request:
```
let res = await sellingPartner.callAPI({
  operation:'createProductReviewAndSellerFeedbackSolicitation',
  path:{
    amazonOrderId:'XXX-XXXXXXX-XXXXXXX'
  },
  query:{
    marketplaceIds:['A1PA6795UKMFR9']
  }
});
```

**Comment by sheshankdebugged** [comment]
Thanks for your valuable reply
Let me try with query and update.

**Comment by sheshankdebugged** [comment]
@amz-tools Thanks It's working fine after adding marketplaceId in query object.
