### ISSUE TITLE
JSON_PARSE_ERROR from listFinancialEvents

### ISSUE THREAD

**Issue by arontolentino** [amz-tools/amazon-sp-api#31]
Hey @amz-tools, we've been experiencing one of the known issues that is mentioned on your repo/library.

We've utilized the raw response option but we're pretty lost on how to actually handle the parsing properly. 

Any idea what the best way to handle these type of errors?

**Comment by amz-tools** [comment]
Hi @arontolentino,

what we do is a regex replace on the raw body and then we are able to parse it:

```
let unknown_chars = {
  '\\\\\\\\xf6':'ö',
  '\\\\\\\\xe4':'ä',
  '\\\\\\\\xfc':'ü',
  '�':'ü',
  '&quot;':'',
  '\\\\–':'-' 
};
for (let unknown_char in unknown_chars) {
  res.body = res.body.replace(new RegExp(unknown_char, 'g'), unknown_chars[unknown_char]);
}
let finance_doc = JSON.parse(res.body.replace(/\n/g, ''));
```
Not very beautiful and I am not sure if this really replaces everything correct, but for our case it works fine, as we don't need the titles etc. but only the financial values and SKUs. So basically the idea for us was to just make it parseable.

**Comment by arontolentino** [comment]
@amz-tools 

We had a breakthrough as well right after I created this issue. 

Our solution is very similar to your solution. We utilized `str.replace(/[^\x20-\x7E]/g, '')` to remove any non_ascii values before we JSON.parse() the processed string.

Same goal as your team - we just needed to get access to the financial values to do some calculations. 

**Side note:** You and your team are amazing. Thank you for all your help so far! I would love to buy your team some coffee on behalf of my team. If there is anyway we can do that, please let me know how.

**Comment by amz-tools** [comment]
@arontolentino,

great! Yours looks a bit nicer than ours though. We might adopt that.

Thanks for the nice feedback! We are definetly coffee junkies, so feel free to send as a pack of coffee, we'd much appreciate it. :-)
Don't know where you're located, you can find our address in our imprint on amz.tools, we are based in Germany.

**Comment by arontolentino** [comment]
@amz-tools You got it! We're from Toronto, Canada. I'll look for some local coffee products and have it delivered to you. I'll notify you once the order has been placed!

**Comment by mee4dy** [comment]
![image](https://user-images.githubusercontent.com/38532197/129979803-5e361591-32ee-4741-a027-3b716abea03d.png)
The same error when there are double quotes in the text

**Comment by mee4dy** [comment]
My solution for double quotes, i'm just replace ProductDescription to another text witout double quotes.

```js
router.get('/finances/:operation', async (req, res) => {
    try {
        let result = null;
        let sellingPartner = initSellingPartner();
        let finances = new Finances(sellingPartner);
        let options = req.query.options ? req.query.options : {};

        if (req.params.operation) {
            result = await finances.callMethod(req.params.operation, options);
        }

        res.send({
            status: true,
            data: result
        });
    } catch (e) {
        if (e.code === 'JSON_PARSE_ERROR') {
            try {
                let jsonResult = JSON.parse(e.message.replace(/\"ProductDescription\"\: \"(.*)\"/g, '"ProductDescription": "deleted"'));

                console.log('jsonResult')

                return res.send({
                    status: true,
                    data: jsonResult.payload
                });
            } catch (e) {}
        }

        res.send({
            status: false,
            msg: e
        });
    }
});
```

**Comment by amz-tools** [comment]
As this is only an issue for finance documents prior to May 2020 and the finances operation only returns data for a maximum of two years of historic data this will be "autofixed" in May 2022.
