### ISSUE TITLE
'The request signature we calculated does not match the signature you provided'. eu-west-1

### ISSUE THREAD

**Issue by carlosdavid-textilesmontecid** [amz-tools/amazon-sp-api#35]
Hi!  I'm trying to make a createFeedDocument operation but the signature doesn't match.
I have been looking at some closed issues (from this library and also from the SP-API), and the error is similar from [This closed issue](https://github.com/amz-tools/amazon-sp-api/issues/23), nevertheless, both content types of my request are the same.
**code**
```
let feed = {
      content:"<?xml version="1.0" encoding="utf-8"?>"
      contentType:"text/xml; charset=utf-8"
    };

    let feed_upload_details = await sellingPartner.callAPI({
      operation:"createFeedDocument",
      body:{
        contentType:feed.contentType
        //I have tried typing directly "text/xml; charset=utf-8"
      }
    });
    console.log(feed_upload_details);  
    let report = await sellingPartner.download(feed_upload_details);
```

**log of feed_upload_details**
{ encryptionDetails:
   { standard: 'AES',
     initializationVector: 'rXLA88xa2w08qyciDOsAkw==',
     key: 'BJchi...' },
  feedDocumentId:
   'amzn1.tortuga.3.2565a8da-1d07-49ad-80cf-da834d5d3ed2.T1Y139K3PX9PFI',
  url:
   'https://tortuga-prod-eu.s3-eu-west-1.amazonaws.com/%2FNinetyDays/amzn1.tortuga.3.2565a8da...' }
   **error of report(download operation)**
{ Error: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at SellingPartner._validateUpOrDownloadSuccess (/)
    at SellingPartner.download (/)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'SignatureDoesNotMatch',
  message:
   'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  type: 'error' }

The URL goes to a most extensive error report (SignatureDoesNotMatch), where the most useful information is that the string to sign has this format:
AWS4-HMAC-SHA256 20210422T061142Z 20210422/eu-west-1/s3/aws4_request cd3fcaa53c9938740839d92bbdaa12275e2c4a5e481d744ff9aa74129f098291

And the Signature provided:
af97666f7c47a9198e02ebff79c042758d4d854667f8dc91c5d5123a45a00736

Another useful information from the URL:
```
<Canonical Request>
GET //NinetyDays/amzn1.tortuga...
...
content-type: host:tortuga-prod-eu.s3-eu-west-1.amazonaws.com content-type;host UNSIGNED-PAYLOAD
</Canonical Request>
```

Thank you very much!

**Comment by amz-tools** [comment]
Hi @carlosdavid-textilesmontecid,

it seems you forgot to upload and create the feed. Once you have called the `createFeedDocument` operation you next step would be calling the `.upload()` function, like this:
`let res = await sellingPartner.upload(feed_upload_details, feed);`

Then you have to call the `createFeed` operation, see the docs [here](https://github.com/amz-tools/amazon-sp-api#encrypt-and-upload-feeds). Only then the feed processing is triggered. You can then use the returned `feedId` to see the status of the processing with the `getFeed` operation and once it has the status `DONE`, you can use the `resultFeedDocumentId` as input for the `getFeedDocument` operation, which then returns the download details that you can then use as input to finally call the `.download()` function, that returns you the result of the uploaded feed.

Quite complicated with a chain of calls there, thats why we already have the plan to add something like a `feed()` function to the client that wraps up all these necessary calls in one function. It will be part of one of the next client releases but no time frame for that yet.

**Comment by carlosdavid-textilesmontecid** [comment]
Hi @amz-tools !

Yes, I was trying to do the whole process but I haven't been returning anything with the .download() function, I thought it was because of the signature error that I was receiving.
As you told me to continue the process, I focused instead on the function (with the debugger tool I could be able to get the body of the response after decrypted) and found that I haven't been declaring the file where I wanted the result.
Now I can see the content of the response.

Thank you very much for the detailed answer, and of course, for the whole library!
