### ISSUE TITLE
TypeScript Types

### ISSUE THREAD

**Issue by dlaudate-embark** [amz-tools/amazon-sp-api#4]
Is there any plan to add TypeScript types across the package?

My team uses TypeScript and are very interested in using this package going forward. We would love to see types here to make the package easier to work with. If there are not plans to add types, would you be open to us making a PR to add some in the future?

**Comment by amz-tools** [comment]
Hi there,

we have no typescript plans on our own, so of course we would appreciate your PR to add typescript types to the module.
