### ISSUE TITLE
Any way to view all (or at least more) offers by ASIN?

### ISSUE THREAD

**Issue by cs-pellsoftware** [amz-tools/amazon-sp-api#42]
When I use the Item Offers API (operation getItemOffers), it will give  a handful of LowestPrices and BuyboxPrices, but only show maybe 5 total offers. In the NumberOfOffers array however, it says there should be 50+ offers.

Is there a different API to view more of the offers? Or any query parameters to utilize?

**Comment by amz-tools** [comment]
@cs-pellsoftware According to the docs the `getItemOffers` operation should return a maximum of 20 offers:

>  A list of offer details. The list is the same length as the TotalOfferCount in the Summary or 20, whichever is less.

**Comment by cs-pellsoftware** [comment]
@amz-tools hmmm my "TotalOfferCount" is 51, but I'm only getting 4 offers.

I think it may be because the "ItemCondition" query is required. Is there a way to mark "All" for that? It doesn't look like there is

**Comment by amz-tools** [comment]
@cs-pellsoftware Don't think so. Seems like you can only pass in one of the enum values. So you would probably have to do multiple calls with different ItemConditions to retrieve more...which is probably what you don't want to do. :-)

**Comment by cs-pellsoftware** [comment]
@amz-tools not ideal but that'll work. Thank you
