### ISSUE TITLE
Update Inventory Price

### ISSUE THREAD

**Issue by ahmetsametoglu** [amz-tools/amazon-sp-api#43]
Hi @amz-tools, 
Thanks for this library, it's really useful and good job!

I want to update the inventory price. I tried 4 different ways but neither worked.
Am I missing something?

I'm working in the European zone.

### Option 1
**listingsItems.patchListingsItem**
_request_
``` ts
 .callAPI({
      operation: 'listingsItems.patchListingsItem',
      path: { sku:[sku], sellerId:[sellerId] },
      query: { marketplaceIds: [marketPlaceId], issueLocale: 'en_US' },
      body: { productType: 'PRODUCT', patches: [{ op: 'replace', path: '/attributes/item-price', value: 19.99 }] },
    })
```
_response_
```
code:'InternalFailure'
details:''
message:'We encountered an internal error. Please try again.'
type:'error'
```
**My opinion:** I think this endpoint has not been implemented yet for Europe.

### Option 2
**JSON_LISTINGS_FEED**
```ts
  const feedType = 'JSON_LISTINGS_FEED';
  const content = {
    header: {
      sellerId: aspConfig.sellerId,
      version: '2.0',
      issueLocale: 'en_US',
    },
    messages: [
      {
        messageId: 1,
        sku: sku,
        operationType: 'PATCH',
        productType: 'PRODUCT',
        patches: [{ op: 'replace', path: '/attributes/listing-price', value: [{ value: price }] }],
      },
    ],
  };

  const contentType = 'application/json; charset=UTF-8';
  const feedUploadDetails = await spService.callAPI({ operation: 'feeds.createFeedDocument', body: { contentType } });

  await spService
    .upload(feedUploadDetails, JSON.stringify(content), contentType)
    .then(res => console.log(res))
    .catch(err => console.log(err));

  const inputFeedDocumentId = feedUploadDetails.feedDocumentId;

  return spService
    .callAPI({
      operation: 'feeds.createFeed',
      body: { feedType, marketplaceIds: [marketPlace.id], inputFeedDocumentId },
    })
    .then(res => console.log(res))
    .catch(err => console.log(err));
```

The feed document was uploaded successfully and also the feed was created successfully, but the status of the feed is IN_PROGRESS for 12 hours. 

```ts
createdTime:'2021-07-16T07:42:27+00:00'
feedId:'138122018824'
feedType:'JSON_LISTINGS_FEED'
marketplaceIds:(1) ['A1PA6795UKMFR9']
processingStartTime:'2021-07-16T07:42:35+00:00'
processingStatus:'IN_PROGRESS'
```
**My opinion**: I think this feed is related to _listingsItems.patchListingsItem_ at the backend so may has the same problem.

### Option 3 & Option 4 
feeds: **POST_FLAT_FILE_INVLOADER_DATA** & **POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA**
```ts
  const feedType = 'POST_FLAT_FILE_INVLOADER_DATA'; // or 'POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA'
  const content = `sku price\n${sku} ${price}`;

  const contentType = 'text/tab-separated-values; charset=UTF-8';

  const feedUploadDetails = await spService.callAPI({ operation: 'feeds.createFeedDocument', body: { contentType } });

  await spService
    .upload(feedUploadDetails, content, contentType)
    .then(res => console.log(res))
    .catch(err => console.log(err));

  const inputFeedDocumentId = feedUploadDetails.feedDocumentId;

  await spService
    .callAPI({
      operation: 'feeds.createFeed',
      body: { feedType, marketplaceIds: [marketPlace.id], inputFeedDocumentId },
    })
    .then(res => console.log(res))
    .catch(err => console.log(err));
```
**feeds status:**
```ts
{  createdTime:'2021-07-17T19:12:48+00:00'
   feedId:'139649018825'
   feedType:'POST_FLAT_FILE_INVLOADER_DATA' 
   marketplaceIds:(1) ['A1PA6795UKMFR9']
   processingStatus:'IN_QUEUE'
}
{
   createdTime:'2021-07-17T16:52:53+00:00'
   feedId:'139397018825'
   feedType:'POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA'  
   marketplaceIds:(1) ['A1PA6795UKMFR9']
   processingStatus:'IN_QUEUE'
}
```
I think I'm going to lose the remaining half of my hair because of seller-partner-api and it's documentation.

Thanks for your help

**Comment by amz-tools** [comment]
Hi @ahmetsametoglu,

one thing you could try is using the `POST_PRODUCT_PRICING_DATA` feed and upload the price update as a xml feed quite similar to the example in the [README](https://github.com/amz-tools/amazon-sp-api#encrypt-and-upload-feeds).

And another thing about the feed processing status we have also noticed with our customers accounts that might be nice to know: Amazon seems to process feeds synchronous one by one and not in parallel. And sometimes a feed gets "stuck" for many hours in the IN_PROGRESS status because of invalid input and is not resolved. This seems to have happened with your option 2 feed too. And as a result your tests with option 3 and 4 will hang IN_QUEUE as option 2 is not processed. So you might retry option 3 and 4 now, maybe one of them works. If you see that option 2 is still in progress you can cancel that feed beforehand with the `cancelFeed` operation.

**Comment by ahmetsametoglu** [comment]
`cancelFeed` does not work like expected. All feeds were canceled, except `JSON_LISTINGS_FEED` the which one is `IN_PROGRESS` status. I think I have to open a case.

**Comment by ahmetsametoglu** [comment]
Did you (@amz-tools) any use `listingsItems.patchListingsItem`? 
I couldn't found any explanation about `path` parameter.

**Comment by amz-tools** [comment]
@ahmetsametoglu No, we didn't. Just had a quick look as well, seems you are not the only one having trouble with the patchListingsItem structure. There's probably no helpful docs or explanation of it (yet). Let us know if you find out how to set the path correct.

**Comment by taofeifanIT** [comment]
i want to add a new product, how to write the `content`
