### ISSUE TITLE
How to get the request IDs?

### ISSUE THREAD

**Issue by emmanuelvr** [amz-tools/amazon-sp-api#47]
Hello there!
We've been using the library for a few months and it has worked nicely for us. Right now we're facing some issues with Amazon's API that we can't find a solution for and we'd like to ask them what's going on. However, in order to do this, we need to send them the request IDs of the specific requests that we see go wrong, but we don't see them anywhere when making the requests through this library. Is there a way we can get the request IDs for our calls?

Thanks in advance.

**Comment by amz-tools** [comment]
Hi @emmanuelvr,

you can set the `raw_result` inside the options object to `true` when using `.callAPI()`. This will return the raw result of the call including the headers which should include the request ID.

**Comment by emmanuelvr** [comment]
I completely missed that, thank you!
