### ISSUE TITLE
productFees.getMyFeesEstimateForASIN InvalidParameterValue

### ISSUE THREAD

**Issue by ahmetsametoglu** [amz-tools/amazon-sp-api#49]
Hi @amz-tools,

I'm trying to get product fees. 
I haven't any problem with other countries (FR, IT, ES, DE) but GB does not work, I'm getting this response:

``` ts
{
  "FeesEstimateResult": {
    "Status": "ClientError",
    "FeesEstimateIdentifier": {
      "MarketplaceId": "A1F83G8C2ARO7P",
      "IdType": "ASIN",
      "SellerId": "XXXXX",
      "SellerInputIdentifier": "56f1174c-b87b-4247-8db5-3ca3798faa1d",
      "IsAmazonFulfilled": true,
      "IdValue": "B00SLIMMHW",
      "PriceToEstimateFees": {
        "ListingPrice": {
          "CurrencyCode": "EUR",
          "Amount": 20
        },
        "Shipping": {
          "CurrencyCode": "EUR",
          "Amount": 0
        }
      }
    },
    "Error": {
      "Type": "Sender",
      "Code": "InvalidParameterValue",
      "Message": "There is an client-side error. Please verify your inputs.",
      "Detail": []
    }
  }
}
```

The error message is not clear. All parameters (except _MarketplaceId_) are the same with other countries but do not work. 
Do you have any idea? 

Thanks !!

**Comment by amz-tools** [comment]
Hi @ahmetsametoglu,

Amazons error message isn't very useful here but I'm quite sure the problem is that you passed in EUR as CurrencyCode instead of GBP.

**Comment by ahmetsametoglu** [comment]
Oh my GOD!
I didn't see. Sorry for keeping you busy. 
Thanks.
