### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dlaudate-embark** [amz-tools/amazon-sp-api#5]
Are there any plans to add tests to the package?

My team is a big proponent of automated testing and noticed this package does not yet have any. We're interesting in using the package going forward and think it would be beneficial to have tests here to verify the functionality as new features are added and changed. If there are not plans for this, would you be open to us making a PR down the line to add tests?

**Comment by amz-tools** [comment]
Yes, we are already on it and will push basic tests for the majority of operations in the near future.

**Comment by dlaudate-embark** [comment]
Excellent, that is great to hear!

**Comment by amz-tools** [comment]
Just added some basic tests.
