### ISSUE TITLE
Getting attributes from getCatalogItem

### ISSUE THREAD

**Issue by steven-so** [amz-tools/amazon-sp-api#52]
Thanks for creating amazon-sp-api. I'm just getting started trying to use the sp-api and it has been super helpful. 

I'm running into some issues getting product attributes from the catalogItem endpoint and was wondering if anyone could help point me in the right direction. Right now my API call looks like this: 

```
await sellingPartner.callAPI({
        operation: "getCatalogItem",
        endpoint: "catalogItems",
        query: {
          marketplaceIds: ["ATVPDKIKX0DER"],
          includedData: ["attributes"],
        },
        path: {
          asin:  <my_asin>,
        },
        options: {
          version: "2020-12-01",
        },
      });
```

If I make the request on asins of certain brands we sell I get this error:
```
CustomError: FORBIDDEN
 ... 
 ... 
 ...
 ...
  details: 'The includedData requested requires Brand Registry affiliation with the requested item. Remove the requested includedData item or register the brand of the item in Brand Registry with the seller.',
  type: 'error'
}
```

Is there a way to set the sellerId? I think the issue is because we are identified as the owner of multiple brands, and it's not assuming the correct sellerId.

**Comment by amz-tools** [comment]
@steven-so,

did you find a solution for your problem? We can confirm we are have been running into the same issue, but I would think it has nothing to do with the sellerId. We are experiencing this also with accounts with only one brand. I works for some products/marketplaces, for others it doesn't.

**Comment by steven-so** [comment]
@amz-tools 

It turns out we were not enrolled with brand registry for that particular brand, but I thought we were.  Our company never went through the brand registry process for that particular brand for whatever reason.
