### ISSUE TITLE
Can only call some endpoints

### ISSUE THREAD

**Issue by SGA-Weld** [amz-tools/amazon-sp-api#65]
I've set up a client:

```
const sellingPartner = new SellingPartnerAPI({
      region: 'eu',
      refresh_token:
        '<Censored>',
      credentials: {
        SELLING_PARTNER_APP_CLIENT_ID: '<censored>',
        SELLING_PARTNER_APP_CLIENT_SECRET: '<censored>',
        AWS_ACCESS_KEY_ID: '<censored>',
        AWS_SECRET_ACCESS_KEY: '<censored>',
        AWS_SELLING_PARTNER_ROLE: '<censored>',
      },
    });

```
And, this works well for getMarketplaceParticipation:

```
const res = await sellingPartner.callAPI({
      operation: 'getMarketplaceParticipations',
      endpoint: 'sellers',
    });
    console.log(res);
```

Gives nice output:

> {
>     marketplace: {
>       id: 'AZMDEXL2RVFNN',
>       countryCode: 'GB',
>       name: 'SI UK Prod Marketplace',
>       defaultCurrencyCode: 'GBP',
>       defaultLanguageCode: 'en_GB',
>       domainName: 'siprodukmarketplace.stores.amazon.co.uk'
>     },
>     participation: { isParticipating: true, hasSuspendedListings: false }
>   }

But, if I try to call getOrderMetrics:

```
const resSales = await sellingPartner.callAPI({
      operation: 'getOrderMetrics',
      endpoint: 'sales',
      query: {
        marketplaceIds: ['A38D8NSA03LJTC'],
        interval: '2020-10-01T00:00:00-07:00--2020-10-01T20:00:00-07:00',
        granularity: 'Hour',
      },
    });
    console.log(resSales);
```
I get the equivalent of "computer says no":

> CustomError: Access to requested resource is denied.
>     at SellingPartner.callAPI (<location>/node_modules/amazon-sp-api/lib/SellingPartner.js:592:13)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async main (<location>) {
>   code: 'Unauthorized',
>   details: '',
>   type: 'error'
> }

Clearly my role, etc., must be setup right, or the first call would not work, I would assume? Any idea why this second call to getOrderMetrics fails?

**Comment by amz-tools** [comment]
Hi @SGA-Weld,

yes, it looks like credentials etc. are set up correct.  I'm wondering where you got the marketplaceId `A38D8NSA03LJTC` from? Here's [a list of valid marketplace ids](https://docs.developer.amazonservices.com/en_UK/dev_guide/DG_Endpoints.html), but it doesn't include the one you are using.

**Comment by SGA-Weld** [comment]
Hi @amz-tools ,

Thanks a lot! Using the ID from the page you linked worked! I used the ID from the getMarketplaceParticipations, but those IDs are apparently not the same! :/ 

So, for those who read this in the future - do NOT use the ID from response from getMarketplaceParticipations, use the ones from @amz-tools link!

**Comment by amz-tools** [comment]
@SGA-Weld, great it works. However when we use the `getMarketplaceParticipations` for our customers, we do get the correct `marketplaceIDs` from the call.

**Comment by SGA-Weld** [comment]
That's very weird... This is the exact response I get, @amz-tools :

> {
>     marketplace: {
>       id: 'A38D8NSA03LJTC',
>       countryCode: 'DE',
>       name: 'Non-Amazon',
>       defaultCurrencyCode: 'EUR',
>       defaultLanguageCode: 'de_DE',
>       domainName: 'si-prod-marketplace-de.stores.amazon.de'
>     },
>     participation: { isParticipating: true, hasSuspendedListings: false }
>   },

I have no good explanation for what might be going on. :/
