### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT] when calling fulfillmentInbound.getShipments().

### ISSUE THREAD

**Issue by harelbaruchi** [amz-tools/amazon-sp-api#69]
I'm fairly new to the sp-api . I have made sure : 1) the client calls successfully the operation 'getMarketPlaceParticipations' of the endpoint : 'sellers.'
2) put all the parameters according to the docs , using a valid date range 
so its configured the right way, the following code suppose to return the inbound shipments for the seller account 

const SellingPartnerAPI= require('amazon-sp-api');

 async function getShipments() {
    try {
        let sellingPartner = new SellingPartnerAPI({
          region:'na', 
          refresh_token:process.env.REFRESH_TOKEN 
        });
        let res = await sellingPartner.callAPI({
          operation:'getShipments',
          endpoint:'fulfillmentInbound',
         
          query: {
              MarketplaceId: 'ATVPDKIKX0DER',
              QueryType: 'DATE_RANGE',
              //what else do i need in here ?
              LastUpdatedAfter: '2021-09-23T08:21:51Z',
              LastUpdatedBefore: '2021-11-19T00:00:00Z',
              ShipmentStatusList: 'WORKING',
          },
        });
        return res;
      } catch(e){
        console.log(e);
      }
}

module.exports={ getShipments}.

I'm receiving the following error to my console : 
 "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client".
what could possibly be written wrong in my API call ., are the parameters written correctly? , please advice , I don't seem to find an example

**Comment by amz-tools** [comment]
Hi @harelbaruchi,

I have never seen this error message in connection with the SP API, but if I understand the `getShipments` documentation correct then you can only provide the `ShipmentStatusList` OR the `LastUpdatedAfter` and `LastUpdatedBefore` params. If you want to use the dates you would have to remove the `ShipmentStatusList` param or else if you want to use the `ShipmentStatusList`, you would have to remove the two dates and set `QueryType` to `SHIPMENT`.

**Comment by harelbaruchi** [comment]
I ran a different script like this one: 

`async function getShipments() {
    try {
        let sellingPartner = new SellingPartnerAPI({
          region:'na', 
          refresh_token:process.env.REFRESH_TOKEN 
        });
        let res = await sellingPartner.callAPI({
          operation:'getShipments',
          endpoint:'fulfillmentInbound',
         
          query: {
              MarketplaceId: 'ATVPDKIKX0DER',
              QueryType: 'SHIPMENT',
              //what else do i need in here ?
              ShipmentStatusList: 'WORKING',
          },
        });
        return res;
      } catch(e){
        console.log(e);
      }
}

and still get the same weird error =" Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client". 
I didn't mention that My seller account has no active shipments at all. could that be the reason?. I do see that my server is still running

**Comment by harelbaruchi** [comment]
hi @amz-tools. thank you for the quick response, I did a mistake in a different part of the program calling the res.json twice. you can close the issue , it was my fault
