### ISSUE TITLE
Shipping get shipment gives me error

### ISSUE THREAD

**Issue by Javadebi** [amz-tools/amazon-sp-api#72]
Hello, I want to get shipment info with this function but gives me this errorL

>  (node:7268) UnhandledPromiseRejectionWarning: Error: We encountered an internal error. Please try again.

 ```
SellingPartnerAPI.callAPI({
          operation: "getShipment",
          //@ts-ignore
          endpoint: "shipping",
          path: {
            shipmentId: "shhhipId",
          },
        }).then((res) => {
          console.log(res);
        });
```

**Comment by amz-tools** [comment]
Hi @Javadebi,

you should add a `.catch` and log the error to get some more information why the call failed.

**Comment by Javadebi** [comment]
> Hi @Javadebi,
> 
> you should add a `.catch` and log the error to get some more information why the call failed.

> CustomError: We encountered an internal error. Please try again.

**Comment by amz-tools** [comment]
Okay, that wasn't a very smart idea, of course the error is the same when catched. :-) 

However I just heard from our team that we encounter the same error message for some of our customers once in a while since 10 hours ago or so. Also with other operations, i.e. reports. It fails randomly and seems to be a problem on Amazons end.

**Comment by Javadebi** [comment]
> Okay, that wasn't a very smart idea, of course the error is the same when catched. :-)
> 
> However I just heard from our team that we encounter the same error message for some of our customers once in a while since 10 hours ago or so. Also with other operations, i.e. reports. It fails randomly and seems to be a problem on Amazons end.

Ok thank you
