### ISSUE TITLE
Shipment plan problem

### ISSUE THREAD

**Issue by Javadebi** [amz-tools/amazon-sp-api#75]
Hi is there any way to send all my products to 1 fulfilment center even though shipment plan seprates them?
I know shipment pro maker does this but I need to know it.

**Comment by amz-tools** [comment]
Hi, I don't think its possible. Amazon itself says:

> When you use the Inventory Placement Service, the destination receive center or fulfillment center is determined by Amazon. You cannot choose the receive center or fulfillment center to which you send your shipment. The destination chosen by Amazon may vary from shipment to shipment.

I am wondering how Shipment Pro Maker is possible to do that, though.
