### ISSUE TITLE
Signing error on getListingsItem

### ISSUE THREAD

**Issue by ydancziger** [amz-tools/amazon-sp-api#77]
Hi I'm getting an error when running the /listings/2021-08-01/items/ with operation `getListingsItem` 

This is error:
`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.The Canonical String for this request should have been'GET/listings/2021-08-01/items/{sellerID}/Wedge%2520Pillow%2520%28Small%29marketplaceIds=A1F83G8C2ARO7Phost:sellingpartnerapi-na.amazon.comx-amz-access-token:Atza|IwEBIDR7jUC0sQKx5feI8CwAEpS4qkCwCFMOG7M3wsFAV9_eXCr3t92br0uYmJzQzTSkGmGXy4VUTE-5cFG7vPZhMlaAAx08ihxp-a2bAzRDyu0hWxqOX8AA7O5Jb-ZmKRQckufj3sMvh2n6zGIiwN7fBRyYzc_I-ZK9mW11ZTK0dhp_PXVl_DKQe7NQ8QHbBNsci-m7G9XDeNsI-HAB0np3wWlUovQZxV1EhT2WTyJg08ogA0ITcj48EkH9NEKPCJOV-KkypTIRp8iUs9plO3N3l-mLfZ2phaTFVIk4QQa8tdUJQGsjzxvrB0lDxueKP3PGf4A5a0U1S-6GS3op6ZoP9sdwx-amz-date:20211206T180148Zhost;x-amz-access-token;x-amz-datee3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'The String-to-Sign should have been'AWS4-HMAC-SHA25620211206T180148Z20211206/us-east-1/execute-api/aws4_requeste80ecfc34ce66f30d6ecc6d659bb7e96689fe1a58a5582e69258e58a5197ba15'`

**Comment by amz-tools** [comment]
Hi @ydancziger,

thanks for finding that bug! Just fixed this in version 0.6.4. The issue was that the parantheses are not encoded by using `encodeURIComponent`. But the SP API expects them to be encoded once, so `(` has to become `%28`.
This same issue occured with a couple more chars (charset `!'()*`). Got this fixed for all of them now.

**Comment by ydancziger** [comment]
Thanks so much for being on it so fast

Also, what can it mean that on some requests I'm getting this error "Access
to requested resource is denied."

**Comment by amz-tools** [comment]
@ydancziger, usually means that you don't have access to the endpoint and/or operation. Which operation are you calling?

**Comment by ydancziger** [comment]
im calling the getListingsItem

**Comment by amz-tools** [comment]
@ydancziger Maybe for some reason you don't have access to some of the SKUs you are requesting?

**Comment by ydancziger** [comment]
Thanks, I'll check it out.

Thanks so much for your amazing and quick help

**Comment by ydancziger** [comment]
I have checked all the SKUs and access and its SKUs from my company, for
some reason I get this access error on some operations, not on all, let's
say on the operations of the order its working fine and I'm getting the
order metrics of my company but when I wanna get listing info I'm getting
this auth error: Access to requested resource is denied.

Can you help me figure this out?

Thanks so much

**Comment by ydancziger** [comment]
Can it be that your package is calling some endpoints wrong so im
getting an access error? i cant another reason why some APIs are working
and some not, i have given the API user and app all access available

**Comment by amz-tools** [comment]
@ydancziger, I think that could be possible, but the error rather indicates that you don't have access. I think we can only find out if you can provide some more details.
