### ISSUE TITLE
Not possible to specify endpoint versions

### ISSUE THREAD

**Issue by erayalakese** [amz-tools/amazon-sp-api#80]
Hello,

I'm trying to call `reports.getReportDocument` operation's specific version `2021-06-30`.

```
const report = await sellingPartner.callAPI({
            operation: 'reports.getReportDocument',
            path: {
                reportDocumentId: reportDocumentId,
            },
            options:{
                version:'2021-06-30'
            }
        });
```

But typescript failing because there is no `options` field on the definition of *ReqParams*

![image](https://user-images.githubusercontent.com/782514/146592056-aab7eae8-66b9-43aa-83a0-94ec1fa287a5.png)

How can I specify the version on `callApi` call?

**Comment by amz-tools** [comment]
Fixed with PR #81
