### ISSUE TITLE
missing type of use_sandbox 

### ISSUE THREAD

**Issue by harelbaruchi** [amz-tools/amazon-sp-api#82]
trying to implement an option to call the sandbox API , in my class instance  : 
```
export class AmzShipments {
	sellingPartner: SellingPartnerAPI;
	public shipmentList: ShipmentItem[];
	public deliverables: Deliverable[];
	public shipmentResult: ShipmentForQuote[];

	constructor(refreshToken: string,useSandBox?: boolean) {
		this.sellingPartner = new SellingPartnerAPI({
			region: 'na',
			refresh_token: refreshToken,
			options: {use_sandbox: useSandBox}
		});
	}
```
i see an Error:  Type '{ use_sandbox: boolean; }' is not assignable to type 'Options'.
  Object literal may only specify known properties, and 'use_sandbox' does not exist in type 'Options'.
After reading more in your docs i realize I'm doing exactly what I'm suppose to do . 
is there a support for use_sandbox in a different version ? 
thanks !

**Comment by amz-tools** [comment]
Hi @harelbaruchi,

the client doesn't not (yet) feature full TypeScript support, so use_sandbox is not yet defined. You may add it in a PR, we will be very much appreciate it.

**Comment by harelbaruchi** [comment]
I did , It's in PR #83. thank you
