### ISSUE TITLE
Order Buyer Info

### ISSUE THREAD

**Issue by mgecmez** [amz-tools/amazon-sp-api#84]
When I call the /orders/v0/orders/{orderId}/buyerInfo SP API call,the structure of the returned value obtained is as follows：

> {"payload":{"AmazonOrderId":" xxxxxxxx","BuyerEmail":"xxxxxxxxx@marketplace.amazon.com"}}

Why have not buyer's name and phone message?

**Comment by amz-tools** [comment]
Hi @mgecmez,

this is probably because you don't have access to PII (Personally Identifiable Information) via the SP API.

**Comment by mgecmez** [comment]
Hi @amz-tools ,

If that's what you're talking about I have it:

![Screenshot 2021-12-28 020021](https://user-images.githubusercontent.com/16095729/147512423-c22c6837-b6d0-4879-95e6-70d5edbbaf14.jpg)

I think that in order to get the 'buyerInfo' and 'shippingAddress' information in the order query, it is necessary to get the restrictedDataToken first.

We were trying to obtain buyerinfo, shippingAddress from the getOrders endpoint (/orders/v0/orders) by requesting a restricted data token using the below requests

> payload= {targetApplication: 'amzn1.sp.solution.xxxx'.'restrictedResources': [{'method':'GET','path':'/orders/v0/orders','dataElements':['shippingAddress','buyerInfo']}]}

We included the access token and necessary authorization headers when making the request but still, we always get 'Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]'.

**Comment by amz-tools** [comment]
I am not sure if that really means that you have access to PII. As far as I know you can successfully retrieve an RDT even if you can't use it due to PII restrictions. I think you would have to clarify that directly with Amazon. I don't think its an issue with the client.

**Comment by mgecmez** [comment]
I guess I solved the problem here. In the developer account, permissions must be obtained for the use of PII. We applied for permits. It hasn't been approved by Amazon yet, but I'll try it after getting approved and I'll share the result here.

**Comment by cpeker-extenship** [comment]
Hello, 
Is the library send any request to the url '/tokens/2021-03-01/restrictedDataToken'

https://github.com/amzn/selling-partner-api-docs/blob/main/references/tokens-api/tokens_2021-03-01.md#createrestricteddatatoken

**Comment by amz-tools** [comment]
HI @cpeker-extenship,

yes, just call it as you would call any other operation. See the following example:

```
let res = await this.sellingPartner.callAPI({
  operation:'tokens.createRestrictedDataToken',
  body:{
    restrictedResources:[{
      path:'/orders/v0/orders',
      method:'GET',
      dataElements:['buyerInfo', 'shippingAddress']
    }]
  }
});
```

**Comment by cpeker-extenship** [comment]
Hi @amz-tools 
Thanks for the suggestion. 
I've reached required fields successfully via calling RDT like you mention above.

**Comment by Hassan99** [comment]
Is there Any update @mgecmez . I am also not getting required information. 

I am getting following response from API

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]",
            "details": ""
        }
    ]
}
