### ISSUE TITLE
Cant find an endpoint for retrieving case packing template 

### ISSUE THREAD

**Issue by harelbaruchi** [amz-tools/amazon-sp-api#85]
I would love to be able to return the packaging list for non-partnered FbaShipments or details of the 
case packed template used in an inbound shipment in the status WORKING, need the info of the dimensions and weights.
please advise

**Comment by amz-tools** [comment]
@harelbaruchi For partnered shipments `getTransportDetails` will return dimensions and weights, but it seems thats not working for non-partnered shipments. According to the [docs](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#nonpartneredsmallparcelpackageoutput), only `CarrierName`, `TrackingId` and `PackageStatus` are returned.
