### ISSUE TITLE
Do I need a signed request in order to get a Restricted Data Token? 

### ISSUE THREAD

**Issue by jamieroyce** [amz-tools/amazon-sp-api#89]
I am using your package to get around creating my own signed request. I got it working for non-restricted requests. Now that I got authorized by Amazon for PII I am trying to get an RDT and add it to your options and having trouble with this. 

I can't find how to generate the RDT using createRestrictedDataToken. What headers do I need for this? Can I use your package to generate my RDT or do I have to do this through the Tokens API?

**Comment by amz-tools** [comment]
Hi @jamieroyce,

yes, you should be able to use the package for creating the RDT. See this example taken from the tests spec:

```
let res = await this.sellingPartner.callAPI({
  operation:'tokens.createRestrictedDataToken',
  body:{
    restrictedResources:[{
      path:'/orders/v0/orders',
      method:'GET',
      dataElements:['buyerInfo', 'shippingAddress']
    }]
  }
});
```

**Comment by jamieroyce** [comment]
Thank you! I am getting this error back even though I was just approved by Amazon to access "Direct-to-Consumer Shipping" Restricted Data: 
`Error: Application does not have access to one or more requested data elements: [buyerInfo], [shippingAddress]`
I generated a new refresh token and tried that, but got same error. 
My "Restricted Access Request" was approved on January 3rd, 2022.
My App is in the "Submitted" status.

**Comment by jamieroyce** [comment]
I just confirmed with Amazon that I should be getting back the Restricted Data Token as my roles are set up and in good standing. 

> I understand that you are having issues with the createRestrictedDataToken function.
> 
> After further investigation it seems like all your Roles are on good standing. Please use the following link as a guide:
> 
> Tutorial: Get authorization to access PII for bulk orders:
> https://github.com/amzn/selling-partner-api-docs/blob/ed29c8398c4de1a034802ff693e0c01359440e55/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-authorization-to-access-pii-for-bulk-orders

**Comment by amz-tools** [comment]
I think the issue might be the `buyerInfo`. The docs state that Direct-to-consumer shipping only allows you to retrieve `shippingAddress`, not `buyerInfo`. So it might be successful if you modify the above call by setting `dataElements` to only include `shippingAddress`?

**Comment by jamieroyce** [comment]
Thanks for the response! I tried it with only the `shippingAddress` and still got the error: 
```(node:226) UnhandledPromiseRejectionWarning: Error: Application does not have access to one or more requested data elements: [shippingAddress]
    at SellingPartner.callAPI (/home/code/mindcloud-api/node_modules/amazon-sp-api/lib/SellingPartner.js:573:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getAmazonOrders (file:///home/code/mindcloud-api/server/lib/jobManager/connectors/amazon/getAmazonOrders.js:17:12)
    at async Object.buildMethod (file:///home/code/mindcloud-api/server/lib/jobManager/jobs/createOrders.js:121:26)
    at async Object.run (file:///home/code/mindcloud-api/server/lib/jobManager/lib/createJobInstance.js:125:34)
    at async Object.runInstance (file:///home/code/mindcloud-api/server/lib/jobManager/lib/createJob.js:54:14)
    at async Object.run (file:///home/code/mindcloud-api/server/lib/jobManager.js:82:16)
    at async file:///home/code/mindcloud-api/server/router/apiRouter.js:72:20
(node:226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:226) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by amz-tools** [comment]
@jamieroyce I think you would probably have to get into contact with Amazon once again, I don't think its an issue with our client.

**Comment by jamieroyce** [comment]
Follow up here. Once Amazon finally approved our account, the above worked. It took about 2 weeks.
