### ISSUE TITLE
Invalid IV length

### ISSUE THREAD

**Issue by lorflea** [amz-tools/amazon-sp-api#91]
While trying to upload a feed with sellingPartner.upload(feed_upload_details, feed) after the createFeedDocument call, I receive the following error:

Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at SellingPartner.upload (/usr/src/server/node_modules/amazon-sp-api/lib/SellingPartner.js:683:27)
    at /usr/src/server/src/stores/amazon/amazonAPI.ts:154:41
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    
This is the object returned by the createFeedDocument:

{
  feedDocumentId: 'DOCUMENT_ID_RETURNED',
  url: 'URL_RETURNED',
  encryptionDetails: {
    standard: 'AES',
    initializationVector: '8f 6c cc 56 0d 50 a2 d0 31 ec 80 be f2 6a 1d 0a',
    key: 'key'
  }
}

I think that the initializationVector is not parsed correctly in the upload function, that treats it as a base64, but still can't find a way to make it work. 

let cipher = crypto.createCipheriv(
        'aes-256-cbc',
        Buffer.from(details.encryptionDetails.key, 'base64'),
        Buffer.from(details.encryptionDetails.initializationVector, 'base64') <-- here
);

Any help will be very appreciated.
Thank you

**Comment by amz-tools** [comment]
Hi @lorflea,

thats quite strange. However you should be able to use the new version of the feeds endpoint which comes without encryption, so it should probably fix you error right away. You can achieve that by adding the version when initializing the client by specifying it in the constructor config options:
```
endpoints_versions:{
  'feeds':'2021-06-30'
}
```
More information on endpoints and versions can be found in the docs:
https://github.com/amz-tools/amazon-sp-api#defining-endpoints-versions-on-class-level

**Comment by amz-tools** [comment]
With the newest version of the endpoint (2021-06-30) the feed content is not encrypted anymore. So I don't think we will ave to deal with the issue as the newest endpoint lacks no features otherwise that would force the usage of the older endpoint version.
