### ISSUE TITLE
How to specify User-Agent while using this SDK?

### ISSUE THREAD

**Issue by erayalakese** [amz-tools/amazon-sp-api#92]
Including custom User-Agent for each requests is a requirement (https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#include-a-user-agent-header-in-all-requests)

How we can specify User-Agent while using this SDK?

**Comment by amz-tools** [comment]
Hi @erayalakese,

you are right, it should be included in every request. Since it works fine without a User-Agent we haven't really put any effort in it, but we should try to add it in a next version, should be easy done to have a default agent and an option to add your own.

**Comment by erayalakese** [comment]
Hello @amz-tools ,

I worked a bit on this. Can you check my PR? https://github.com/amz-tools/amazon-sp-api/pull/93

**Comment by amz-tools** [comment]
Has been added in version 0.6.6.
