### ISSUE TITLE
No option to call with "RestrictedDataToken"

### ISSUE THREAD

**Issue by nabeel-sajid-qbatch** [amz-tools/amazon-sp-api#94]
I was able to create RDT token using the following helper

`const response = await client.callAPI({
    operation: "tokens.createRestrictedDataToken",
    body: {
      restrictedResources: [
        {
          path: `/reports/2021-06-30/documents/${reportDocumentId}`,
          method: "GET",
          dataElements: ["buyerInfo", "shippingAddress"],
        },
      ],
    },
  });`
  
 but there is no option to call the client with this RDT token
 kindly help

**Comment by amz-tools** [comment]
Hi @nabeel-sajid-qbatch,

there is an option, you just need to add the token as `restricted_data_token` to `.callAPI()`, see the following example:
```
const buyer_info = await client.callAPI({
  operation:'orders.getOrderAddress',
  path:{
    orderId:'XXX-XXXXXXX-XXXXXXX'
  },
  restricted_data_token:'FILL_IN_THE_RDT_HERE'
});
```

**Comment by nabeelasjid1** [comment]
Thank you @amz-tools it really helped me to solve the problem, 
there was another issue as well, i needed to pass the version: "2021-06-30" in options, because the restricted reports was missing in default version user by the library

**Comment by Philomath88** [comment]
@nabeelasjid1 Any chance you could show me how you create the RDT and use it in the call? I am struggling with that

**Comment by nabeelasjid1** [comment]
Yes sure.

{{endpoint}}/tokens/2021-03-01/restrictedDataToken

{
    "restrictedResources": [
        {
            "method": "GET",
            "path": "/orders/v0/orders",
            "dataElements": [
            "buyerInfo",
            "shippingAddress"
        ]
    }
]
}
