### ISSUE TITLE
Access to the resource is forbidden

### ISSUE THREAD

**Issue by Javadebi** [amz-tools/amazon-sp-api#96]
Hi I want to create report of type `GET_PROMOTION_PERFORMANCE_REPORT` but I get

> Access to the resource is forbidden

My account access is:
![PII](https://user-images.githubusercontent.com/37909821/151431592-f8f82e14-78d0-4992-a993-0fa64180cfbd.jpg)

**Comment by amz-tools** [comment]
Hi @Javadebi,

I don't think there are any restrictions on that report. The report works fine for all of our customers. Did you pass the `promotionStartDateFrom` and `promotionStartDateTo` as `reportOptions`? These are mandatory.

**Comment by Javadebi** [comment]
I have passed them. Do you guys know any good npm package for amazon advertising api?

> Hi @Javadebi,
> 
> I don't think there are any restrictions on that report. The report works fine for all of our customers. Did you pass the `promotionStartDateFrom` and `promotionStartDateTo` as `reportOptions`? These are mandatory.

**Comment by amz-tools** [comment]
Hi @Javadebi,

we started creating a package for the Amazon Advertising Api as well, you can [find it here](https://github.com/amz-tools/amazon-ad-api).
Its structure is comparable to the one from this package, but it is still very very much at the start, so I wouldn't recommend using it yet and its also not published yet.

Apart from that, the Amazon Advertising API is quite a lot simpler than the Selling Partner API (i.e. no AWS4 signing), so it shouldn't be too hard to handle the API without a package.
